// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_SCHEDULER$_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_SCHEDULER$_H_

#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace cppproxy { struct SpoolerC; }}}}}}}
namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { struct Scheduler; }}}}}}
namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace main { struct SchedulerControllerBridge; }}}}}}
namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { 


struct Scheduler$__class;

struct Scheduler$ : ::zschimmer::javabridge::proxy_jobject< Scheduler$ >, ::javaproxy::java::lang::Object {
  private:
    static Scheduler$ new_instance();  // Not implemented
  public:

    Scheduler$(jobject = NULL);

    Scheduler$(const Scheduler$&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Scheduler$(Scheduler$&&);
    #endif

    ~Scheduler$();

    Scheduler$& operator=(jobject jo) { assign_(jo); return *this; }
    Scheduler$& operator=(const Scheduler$& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Scheduler$& operator=(Scheduler$&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< Scheduler$ >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< Scheduler$ >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    ::javaproxy::com::sos::scheduler::engine::kernel::Scheduler of(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::kernel::cppproxy::SpoolerC >& p0, const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::main::SchedulerControllerBridge >& p1, const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p2) const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<Scheduler$__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}}}

#endif
