// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_CPPPROXY_JOB_NODEC_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_CPPPROXY_JOB_NODEC_H_

#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace cppproxy { struct JobC; }}}}}}}
namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace cppproxy { 


struct Job_nodeC__class;

struct Job_nodeC : ::zschimmer::javabridge::proxy_jobject< Job_nodeC >, ::javaproxy::java::lang::Object {
  private:
    static Job_nodeC new_instance();  // Not implemented
  public:

    Job_nodeC(jobject = NULL);

    Job_nodeC(const Job_nodeC&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Job_nodeC(Job_nodeC&&);
    #endif

    ~Job_nodeC();

    Job_nodeC& operator=(jobject jo) { assign_(jo); return *this; }
    Job_nodeC& operator=(const Job_nodeC& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Job_nodeC& operator=(Job_nodeC&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< Job_nodeC >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< Job_nodeC >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:


    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<Job_nodeC__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}}}}

#endif
