// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__cppproxy__Task_subsystemC.h"
#include "com__sos__scheduler__engine__kernel__cppproxy__TaskC.h"
#include "java__lang__Object.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace cppproxy { 

struct Task_subsystemC__class : ::zschimmer::javabridge::Class
{
    Task_subsystemC__class(const string& class_name);
   ~Task_subsystemC__class();


    static const ::zschimmer::javabridge::class_factory< Task_subsystemC__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< Task_subsystemC__class > Task_subsystemC__class::class_factory ("com.sos.scheduler.engine.kernel.cppproxy.Task_subsystemC");

Task_subsystemC__class::Task_subsystemC__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
{}

Task_subsystemC__class::~Task_subsystemC__class() {}




Task_subsystemC::Task_subsystemC(jobject jo) { if (jo) assign_(jo); }

Task_subsystemC::Task_subsystemC(const Task_subsystemC& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    Task_subsystemC::Task_subsystemC(Task_subsystemC&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

Task_subsystemC::~Task_subsystemC() { assign_(NULL); }





::zschimmer::javabridge::Class* Task_subsystemC::java_object_class_() const { return _class.get(); }

::zschimmer::javabridge::Class* Task_subsystemC::java_class_() { return Task_subsystemC__class::class_factory.clas(); }


void Task_subsystemC::Lazy_class::initialize() const {
    _value = Task_subsystemC__class::class_factory.clas();
}


}}}}}}}
