// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_FOLDER_FILEBASED_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_FOLDER_FILEBASED_H_

#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace cplusplus { namespace runtime { struct Sister; }}}}}}}
namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace folder { 


struct FileBased__class;

struct FileBased : ::zschimmer::javabridge::proxy_jobject< FileBased >, ::javaproxy::java::lang::Object {
  private:
    static FileBased new_instance();  // Not implemented
  public:

    FileBased(jobject = NULL);

    FileBased(const FileBased&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        FileBased(FileBased&&);
    #endif

    ~FileBased();

    FileBased& operator=(jobject jo) { assign_(jo); return *this; }
    FileBased& operator=(const FileBased& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        FileBased& operator=(FileBased&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< FileBased >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< FileBased >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:


    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<FileBased__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}}}}

#endif
