// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_ORDERSTATECHANGEDEVENT_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_ORDERSTATECHANGEDEVENT_H_

#include "com__sos__scheduler__engine__eventbus__AbstractEvent.h"
#include "com__sos__scheduler__engine__kernel__order__OrderEvent.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { struct OrderEvent; }}}}}}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { 


struct OrderStateChangedEvent__class;

struct OrderStateChangedEvent : ::zschimmer::javabridge::proxy_jobject< OrderStateChangedEvent >, ::javaproxy::com::sos::scheduler::engine::kernel::order::OrderEvent {
  private:
    static OrderStateChangedEvent new_instance();  // Not implemented
  public:

    OrderStateChangedEvent(jobject = NULL);

    OrderStateChangedEvent(const OrderStateChangedEvent&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        OrderStateChangedEvent(OrderStateChangedEvent&&);
    #endif

    ~OrderStateChangedEvent();

    OrderStateChangedEvent& operator=(jobject jo) { assign_(jo); return *this; }
    OrderStateChangedEvent& operator=(const OrderStateChangedEvent& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        OrderStateChangedEvent& operator=(OrderStateChangedEvent&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< OrderStateChangedEvent >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< OrderStateChangedEvent >::set_jobject(jo);
        ::javaproxy::com::sos::scheduler::engine::kernel::order::OrderEvent::set_jobject(jo);
    }
  public:

    static ::javaproxy::com::sos::scheduler::engine::kernel::order::OrderStateChangedEvent of(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0, const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p1, const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p2);

    ::zschimmer::javabridge::Class* java_object_class_();

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<OrderStateChangedEvent__class*> {
        void initialize();
    };

    Lazy_class _class;
};


}}}}}}}

#endif
