// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_HTTP_SCHEDULERHTTPREQUEST_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_HTTP_SCHEDULERHTTPREQUEST_H_

#include "java__lang__Object.h"

namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace http { 


struct SchedulerHttpRequest__class;

struct SchedulerHttpRequest : ::zschimmer::javabridge::proxy_jobject< SchedulerHttpRequest >, ::javaproxy::java::lang::Object {
  private:
    static SchedulerHttpRequest new_instance();  // Not implemented
  public:

    SchedulerHttpRequest(jobject = NULL);

    SchedulerHttpRequest(const SchedulerHttpRequest&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        SchedulerHttpRequest(SchedulerHttpRequest&&);
    #endif

    ~SchedulerHttpRequest();

    SchedulerHttpRequest& operator=(jobject jo) { assign_(jo); return *this; }
    SchedulerHttpRequest& operator=(const SchedulerHttpRequest& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        SchedulerHttpRequest& operator=(SchedulerHttpRequest&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< SchedulerHttpRequest >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< SchedulerHttpRequest >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    ::javaproxy::java::lang::String body();
    ::javaproxy::java::lang::String charsetName();
    bool hasParameter(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0);
    ::javaproxy::java::lang::String header(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0);
    ::javaproxy::java::lang::String httpMethod();
    ::javaproxy::java::lang::String parameter(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0);
    ::javaproxy::java::lang::String protocol();
    ::javaproxy::java::lang::String urlPath();

    ::zschimmer::javabridge::Class* java_object_class_();

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<SchedulerHttpRequest__class*> {
        void initialize();
    };

    Lazy_class _class;
};


}}}}}}}

#endif
