// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__order__OrderStepStartedEvent.h"
#include "com__sos__scheduler__engine__kernel__order__ModifiableOrderEvent.h"
#include "com__sos__scheduler__engine__kernel__order__Order.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { 

struct OrderStepStartedEvent__class : ::zschimmer::javabridge::Class
{
    OrderStepStartedEvent__class(const string& class_name);
   ~OrderStepStartedEvent__class();

    ::zschimmer::javabridge::Method const __constructor__Lcom_sos_scheduler_engine_kernel_order_Order_2__method;

    static const ::zschimmer::javabridge::class_factory< OrderStepStartedEvent__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< OrderStepStartedEvent__class > OrderStepStartedEvent__class::class_factory ("com.sos.scheduler.engine.kernel.order.OrderStepStartedEvent");

OrderStepStartedEvent__class::OrderStepStartedEvent__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
    ,__constructor__Lcom_sos_scheduler_engine_kernel_order_Order_2__method(this, "<init>", "(Lcom/sos/scheduler/engine/kernel/order/Order;)V"){}

OrderStepStartedEvent__class::~OrderStepStartedEvent__class() {}



OrderStepStartedEvent OrderStepStartedEvent::new_instance(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::kernel::order::Order >& p0) {
    OrderStepStartedEvent result;
    result.java_object_allocate_();
    ::zschimmer::javabridge::raw_parameter_list<1> parameter_list;
    parameter_list._jvalues[0].l = p0.get_jobject();
    OrderStepStartedEvent__class* cls = result._class.get();
    cls->__constructor__Lcom_sos_scheduler_engine_kernel_order_Order_2__method.call(result.get_jobject(), parameter_list);
    return result;
}


OrderStepStartedEvent::OrderStepStartedEvent(jobject jo) { if (jo) assign_(jo); }

OrderStepStartedEvent::OrderStepStartedEvent(const OrderStepStartedEvent& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    OrderStepStartedEvent::OrderStepStartedEvent(OrderStepStartedEvent&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

OrderStepStartedEvent::~OrderStepStartedEvent() { assign_(NULL); }





::zschimmer::javabridge::Class* OrderStepStartedEvent::java_object_class_() { return _class.get(); }

::zschimmer::javabridge::Class* OrderStepStartedEvent::java_class_() { return OrderStepStartedEvent__class::class_factory.clas(); }


void OrderStepStartedEvent::Lazy_class::initialize() {
    _value = OrderStepStartedEvent__class::class_factory.clas();
}


}}}}}}}
