// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__cppproxy__Standing_order_subsystemC.h"
#include "java__lang__Object.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace cppproxy { 

struct Standing_order_subsystemC__class : ::zschimmer::javabridge::Class
{
    Standing_order_subsystemC__class(const string& class_name);
   ~Standing_order_subsystemC__class();


    static const ::zschimmer::javabridge::class_factory< Standing_order_subsystemC__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< Standing_order_subsystemC__class > Standing_order_subsystemC__class::class_factory ("com.sos.scheduler.engine.kernel.cppproxy.Standing_order_subsystemC");

Standing_order_subsystemC__class::Standing_order_subsystemC__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
{}

Standing_order_subsystemC__class::~Standing_order_subsystemC__class() {}




Standing_order_subsystemC::Standing_order_subsystemC(jobject jo) { if (jo) assign_(jo); }

Standing_order_subsystemC::Standing_order_subsystemC(const Standing_order_subsystemC& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    Standing_order_subsystemC::Standing_order_subsystemC(Standing_order_subsystemC&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

Standing_order_subsystemC::~Standing_order_subsystemC() { assign_(NULL); }





::zschimmer::javabridge::Class* Standing_order_subsystemC::java_object_class_() const { return _class.get(); }

::zschimmer::javabridge::Class* Standing_order_subsystemC::java_class_() { return Standing_order_subsystemC__class::class_factory.clas(); }


void Standing_order_subsystemC::Lazy_class::initialize() const {
    _value = Standing_order_subsystemC__class::class_factory.clas();
}


}}}}}}}
