// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_ORDERSUBSYSTEM_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_ORDERSUBSYSTEM_H_

#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { namespace jobchain { struct Node; }}}}}}}}
namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { 


struct OrderSubsystem__class;

struct OrderSubsystem : ::zschimmer::javabridge::proxy_jobject< OrderSubsystem >, ::javaproxy::java::lang::Object {
  private:
    static OrderSubsystem new_instance();  // Not implemented
  public:

    OrderSubsystem(jobject = NULL);

    OrderSubsystem(const OrderSubsystem&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        OrderSubsystem(OrderSubsystem&&);
    #endif

    ~OrderSubsystem();

    OrderSubsystem& operator=(jobject jo) { assign_(jo); return *this; }
    OrderSubsystem& operator=(const OrderSubsystem& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        OrderSubsystem& operator=(OrderSubsystem&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< OrderSubsystem >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< OrderSubsystem >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    void persistNodeState(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::kernel::order::jobchain::Node >& p0) const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<OrderSubsystem__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}}}}

#endif
