// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_PROCESSCLASS_AGENT_CPPHTTPREMOTEAPIPROCESSCLIENT_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_PROCESSCLASS_AGENT_CPPHTTPREMOTEAPIPROCESSCLIENT_H_

#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace processclass { namespace agent { 


struct CppHttpRemoteApiProcessClient__class;

struct CppHttpRemoteApiProcessClient : ::zschimmer::javabridge::proxy_jobject< CppHttpRemoteApiProcessClient >, ::javaproxy::java::lang::Object {
  private:
    static CppHttpRemoteApiProcessClient new_instance();  // Not implemented
  public:

    CppHttpRemoteApiProcessClient(jobject = NULL);

    CppHttpRemoteApiProcessClient(const CppHttpRemoteApiProcessClient&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        CppHttpRemoteApiProcessClient(CppHttpRemoteApiProcessClient&&);
    #endif

    ~CppHttpRemoteApiProcessClient();

    CppHttpRemoteApiProcessClient& operator=(jobject jo) { assign_(jo); return *this; }
    CppHttpRemoteApiProcessClient& operator=(const CppHttpRemoteApiProcessClient& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        CppHttpRemoteApiProcessClient& operator=(CppHttpRemoteApiProcessClient&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< CppHttpRemoteApiProcessClient >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< CppHttpRemoteApiProcessClient >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    void closeRemoteTask() const;
    bool killRemoteTask() const;
    ::javaproxy::java::lang::String toString() const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<CppHttpRemoteApiProcessClient__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}}}}}

#endif
