// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__folder__events__FileBasedRemovedEvent.h"
#include "com__sos__scheduler__engine__kernel__event__ObjectEvent.h"
#include "com__sos__scheduler__engine__kernel__folder__FileBased.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace folder { namespace events { 

struct FileBasedRemovedEvent__class : ::zschimmer::javabridge::Class
{
    FileBasedRemovedEvent__class(const string& class_name);
   ~FileBasedRemovedEvent__class();

    ::zschimmer::javabridge::Method const __constructor__Lcom_sos_scheduler_engine_kernel_folder_FileBased_2__method;

    static const ::zschimmer::javabridge::class_factory< FileBasedRemovedEvent__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< FileBasedRemovedEvent__class > FileBasedRemovedEvent__class::class_factory ("com.sos.scheduler.engine.kernel.folder.events.FileBasedRemovedEvent");

FileBasedRemovedEvent__class::FileBasedRemovedEvent__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
    ,__constructor__Lcom_sos_scheduler_engine_kernel_folder_FileBased_2__method(this, "<init>", "(Lcom/sos/scheduler/engine/kernel/folder/FileBased;)V"){}

FileBasedRemovedEvent__class::~FileBasedRemovedEvent__class() {}



FileBasedRemovedEvent FileBasedRemovedEvent::new_instance(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::kernel::folder::FileBased >& p0) {
    FileBasedRemovedEvent result;
    result.java_object_allocate_();
    ::zschimmer::javabridge::raw_parameter_list<1> parameter_list;
    parameter_list._jvalues[0].l = p0.get_jobject();
    FileBasedRemovedEvent__class* cls = result._class.get();
    cls->__constructor__Lcom_sos_scheduler_engine_kernel_folder_FileBased_2__method.call(result.get_jobject(), parameter_list);
    return result;
}


FileBasedRemovedEvent::FileBasedRemovedEvent(jobject jo) { if (jo) assign_(jo); }

FileBasedRemovedEvent::FileBasedRemovedEvent(const FileBasedRemovedEvent& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    FileBasedRemovedEvent::FileBasedRemovedEvent(FileBasedRemovedEvent&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

FileBasedRemovedEvent::~FileBasedRemovedEvent() { assign_(NULL); }





::zschimmer::javabridge::Class* FileBasedRemovedEvent::java_object_class_() { return _class.get(); }

::zschimmer::javabridge::Class* FileBasedRemovedEvent::java_class_() { return FileBasedRemovedEvent__class::class_factory.clas(); }


void FileBasedRemovedEvent::Lazy_class::initialize() {
    _value = FileBasedRemovedEvent__class::class_factory.clas();
}


}}}}}}}}
