// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_ORG_W3C_DOM_TEXT_H_
#define _JAVAPROXY_ORG_W3C_DOM_TEXT_H_

#include "java__lang__Object.h"

namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}
namespace javaproxy { namespace org { namespace w3c { namespace dom { struct CharacterData; }}}}


namespace javaproxy { namespace org { namespace w3c { namespace dom { 


struct Text__class;

struct Text : ::zschimmer::javabridge::proxy_jobject< Text >, ::javaproxy::java::lang::Object {
  private:
    static Text new_instance();  // Not implemented
  public:

    Text(jobject = NULL);

    Text(const Text&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Text(Text&&);
    #endif

    ~Text();

    Text& operator=(jobject jo) { assign_(jo); return *this; }
    Text& operator=(const Text& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Text& operator=(Text&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< Text >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< Text >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    ::javaproxy::java::lang::String getWholeText() const;
    bool isElementContentWhitespace() const;
    ::javaproxy::org::w3c::dom::Text replaceWholeText(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0) const;
    ::javaproxy::org::w3c::dom::Text splitText(jint p0) const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<Text__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}

#endif
