// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_ORG_W3C_DOM_COMMENT_H_
#define _JAVAPROXY_ORG_W3C_DOM_COMMENT_H_

#include "_precompiled.h"

#include "java__lang__Object.h"

namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}
namespace javaproxy { namespace org { namespace w3c { namespace dom { struct CharacterData; }}}}


namespace javaproxy { namespace org { namespace w3c { namespace dom { 


struct Comment__class;

struct Comment : ::zschimmer::javabridge::proxy_jobject< Comment >, ::javaproxy::java::lang::Object {
  private:
    static Comment new_instance();  // Not implemented
  public:

    Comment(jobject = NULL);

    Comment(const Comment&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Comment(Comment&&);
    #endif

    ~Comment();

    Comment& operator=(jobject jo) { assign_(jo); return *this; }
    Comment& operator=(const Comment& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Comment& operator=(Comment&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< Comment >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< Comment >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:


    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<Comment__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}

#endif
