// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_ORG_W3C_DOM_CHARACTERDATA_H_
#define _JAVAPROXY_ORG_W3C_DOM_CHARACTERDATA_H_

#include "java__lang__Object.h"

namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}
namespace javaproxy { namespace org { namespace w3c { namespace dom { struct Node; }}}}


namespace javaproxy { namespace org { namespace w3c { namespace dom { 


struct CharacterData__class;

struct CharacterData : ::zschimmer::javabridge::proxy_jobject< CharacterData >, ::javaproxy::java::lang::Object {
  private:
    static CharacterData new_instance();  // Not implemented
  public:

    CharacterData(jobject = NULL);

    CharacterData(const CharacterData&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        CharacterData(CharacterData&&);
    #endif

    ~CharacterData();

    CharacterData& operator=(jobject jo) { assign_(jo); return *this; }
    CharacterData& operator=(const CharacterData& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        CharacterData& operator=(CharacterData&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< CharacterData >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< CharacterData >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    void appendData(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0) const;
    void deleteData(jint p0, jint p1) const;
    ::javaproxy::java::lang::String getData() const;
    jint getLength() const;
    void insertData(jint p0, const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p1) const;
    void replaceData(jint p0, jint p1, const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p2) const;
    void setData(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0) const;
    ::javaproxy::java::lang::String substringData(jint p0, jint p1) const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<CharacterData__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}

#endif
