// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_ORG_JODA_TIME_DATETIME_H_
#define _JAVAPROXY_ORG_JODA_TIME_DATETIME_H_

#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"
#include "java__lang__Object.h"
#include "org__joda__time__base__AbstractDateTime.h"
#include "org__joda__time__base__AbstractInstant.h"
#include "org__joda__time__base__BaseDateTime.h"

namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}
namespace javaproxy { namespace org { namespace joda { namespace time { namespace base { struct BaseDateTime; }}}}}


namespace javaproxy { namespace org { namespace joda { namespace time { 


struct DateTime__class;

struct DateTime : ::zschimmer::javabridge::proxy_jobject< DateTime >, ::javaproxy::org::joda::time::base::BaseDateTime {
    static DateTime new_instance();
    static DateTime new_instance(jint p0, jint p1, jint p2, jint p3, jint p4);
    static DateTime new_instance(jint p0, jint p1, jint p2, jint p3, jint p4, jint p5);
    static DateTime new_instance(jint p0, jint p1, jint p2, jint p3, jint p4, jint p5, jint p6);
    static DateTime new_instance(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p0);
    static DateTime new_instance(jlong p0);

    DateTime(jobject = NULL);

    DateTime(const DateTime&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        DateTime(DateTime&&);
    #endif

    ~DateTime();

    DateTime& operator=(jobject jo) { assign_(jo); return *this; }
    DateTime& operator=(const DateTime& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        DateTime& operator=(DateTime&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< DateTime >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< DateTime >::set_jobject(jo);
        ::javaproxy::org::joda::time::base::BaseDateTime::set_jobject(jo);
    }
  public:

    ::javaproxy::org::joda::time::DateTime minus(jlong p0) const;
    ::javaproxy::org::joda::time::DateTime minusDays(jint p0) const;
    ::javaproxy::org::joda::time::DateTime minusHours(jint p0) const;
    ::javaproxy::org::joda::time::DateTime minusMillis(jint p0) const;
    ::javaproxy::org::joda::time::DateTime minusMinutes(jint p0) const;
    ::javaproxy::org::joda::time::DateTime minusMonths(jint p0) const;
    ::javaproxy::org::joda::time::DateTime minusSeconds(jint p0) const;
    ::javaproxy::org::joda::time::DateTime minusWeeks(jint p0) const;
    ::javaproxy::org::joda::time::DateTime minusYears(jint p0) const;
    static ::javaproxy::org::joda::time::DateTime now();
    static ::javaproxy::org::joda::time::DateTime parse(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0);
    ::javaproxy::org::joda::time::DateTime plus(jlong p0) const;
    ::javaproxy::org::joda::time::DateTime plusDays(jint p0) const;
    ::javaproxy::org::joda::time::DateTime plusHours(jint p0) const;
    ::javaproxy::org::joda::time::DateTime plusMillis(jint p0) const;
    ::javaproxy::org::joda::time::DateTime plusMinutes(jint p0) const;
    ::javaproxy::org::joda::time::DateTime plusMonths(jint p0) const;
    ::javaproxy::org::joda::time::DateTime plusSeconds(jint p0) const;
    ::javaproxy::org::joda::time::DateTime plusWeeks(jint p0) const;
    ::javaproxy::org::joda::time::DateTime plusYears(jint p0) const;
    ::javaproxy::org::joda::time::DateTime toDateTime() const;
    ::javaproxy::org::joda::time::DateTime toDateTimeISO() const;
    ::javaproxy::org::joda::time::DateTime withCenturyOfEra(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withDate(jint p0, jint p1, jint p2) const;
    ::javaproxy::org::joda::time::DateTime withDayOfMonth(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withDayOfWeek(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withDayOfYear(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withDurationAdded(jlong p0, jint p1) const;
    ::javaproxy::org::joda::time::DateTime withEarlierOffsetAtOverlap() const;
    ::javaproxy::org::joda::time::DateTime withEra(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withHourOfDay(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withLaterOffsetAtOverlap() const;
    ::javaproxy::org::joda::time::DateTime withMillis(jlong p0) const;
    ::javaproxy::org::joda::time::DateTime withMillisOfDay(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withMillisOfSecond(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withMinuteOfHour(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withMonthOfYear(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withSecondOfMinute(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withTime(jint p0, jint p1, jint p2, jint p3) const;
    ::javaproxy::org::joda::time::DateTime withTimeAtStartOfDay() const;
    ::javaproxy::org::joda::time::DateTime withWeekOfWeekyear(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withWeekyear(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withYear(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withYearOfCentury(jint p0) const;
    ::javaproxy::org::joda::time::DateTime withYearOfEra(jint p0) const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<DateTime__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}

#endif
