// *** Generated by com.sos.cplusplus.generator ***
#include "spooler.h"
#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_java_proxy.h"

using namespace ::zschimmer;
using namespace ::zschimmer::javabridge;

namespace zschimmer { namespace javabridge { 

    template<> const class_factory<Java_proxy_class> has_java_proxy< ::sos::scheduler::Job_subsystem >::java_proxy_class_factory("com.sos.scheduler.intern.cppproxy.Job_subsystemCImpl");

}}

extern "C" jobject JNICALL Java_com_sos_scheduler_intern_cppproxy_Job_1subsystemC_job_1by_1string__Ljava_lang_String_2(JNIEnv* jenv, jobject, jlong cppReference, jstring p0)
{
    Env env = jenv;
    try {
        return (has_java_proxy< ::sos::scheduler::Job_subsystem >::of_java_proxy_cpp_reference(cppReference)->job_by_string(env.string_from_jstring(p0)))->get_jobject();
    }
    catch(const exception& x) {
        env.set_java_exception(x);
        return jobject();
    }
}

extern "C" jobject JNICALL Java_com_sos_scheduler_intern_cppproxy_Job_1subsystemC_job_1by_1string_1or_1null__Ljava_lang_String_2(JNIEnv* jenv, jobject, jlong cppReference, jstring p0)
{
    Env env = jenv;
    try {
        return (has_java_proxy< ::sos::scheduler::Job_subsystem >::of_java_proxy_cpp_reference(cppReference)->job_by_string_or_null(env.string_from_jstring(p0)))->get_jobject();
    }
    catch(const exception& x) {
        env.set_java_exception(x);
        return jobject();
    }
}

const static JNINativeMethod native_methods[] = {
{ "job_by_string__native", "(JLjava/lang/String;)Lcom/sos/scheduler/intern/cppproxy/JobC;", (void*)Java_com_sos_scheduler_intern_cppproxy_Job_1subsystemC_job_1by_1string__Ljava_lang_String_2 },
{ "job_by_string_or_null__native", "(JLjava/lang/String;)Lcom/sos/scheduler/intern/cppproxy/JobC;", (void*)Java_com_sos_scheduler_intern_cppproxy_Job_1subsystemC_job_1by_1string_1or_1null__Ljava_lang_String_2 }
};

namespace zschimmer { namespace javabridge { 

    template<> void has_java_proxy<::sos::scheduler::Job_subsystem>::initialize_java_proxy() {
        Env env;
        Class* cls = ::sos::scheduler::Job_subsystem::java_proxy_class_factory.clas();
        int ret = env->RegisterNatives(*cls, native_methods, NO_OF(native_methods));
        if (ret < 0)  env.throw_java("RegisterNatives");
    }

}}
