// *** Generated by com.sos.scheduler.kernel.cplusplus.generator ***

#include "spooler.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"

using namespace ::zschimmer;
using namespace ::zschimmer::javabridge;

namespace zschimmer { namespace javabridge { 

    template<> const class_factory<Proxy_class> has_proxy< ::sos::scheduler::order::job_chain::Node >::proxy_class_factory("com.sos.scheduler.kernel.core.cppproxy.NodeCImpl");

}}

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace kernel { namespace core { namespace cppproxy { 

static jstring JNICALL string_1error_1state(JNIEnv* jenv, jobject, jlong cppReference)
{
    Env env = jenv;
    try {
        ::sos::scheduler::order::job_chain::Node* o_ = has_proxy<::sos::scheduler::order::job_chain::Node>::of_cpp_reference(cppReference,"::sos::scheduler::order::job_chain::Node::string_error_state()");
        return env.jstring_from_string(o_->string_error_state());
    }
    catch(const exception& x) {
        env.set_java_exception(x);
        return jstring();
    }
}

}}}}}}}

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace kernel { namespace core { namespace cppproxy { 

static jstring JNICALL string_1next_1state(JNIEnv* jenv, jobject, jlong cppReference)
{
    Env env = jenv;
    try {
        ::sos::scheduler::order::job_chain::Node* o_ = has_proxy<::sos::scheduler::order::job_chain::Node>::of_cpp_reference(cppReference,"::sos::scheduler::order::job_chain::Node::string_next_state()");
        return env.jstring_from_string(o_->string_next_state());
    }
    catch(const exception& x) {
        env.set_java_exception(x);
        return jstring();
    }
}

}}}}}}}

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace kernel { namespace core { namespace cppproxy { 

static jstring JNICALL string_1order_1state(JNIEnv* jenv, jobject, jlong cppReference)
{
    Env env = jenv;
    try {
        ::sos::scheduler::order::job_chain::Node* o_ = has_proxy<::sos::scheduler::order::job_chain::Node>::of_cpp_reference(cppReference,"::sos::scheduler::order::job_chain::Node::string_order_state()");
        return env.jstring_from_string(o_->string_order_state());
    }
    catch(const exception& x) {
        env.set_java_exception(x);
        return jstring();
    }
}

}}}}}}}

const static JNINativeMethod native_methods[] = {
    { "string_error_state__native", "(J)Ljava/lang/String;", (void*)::javaproxy::com::sos::scheduler::kernel::core::cppproxy::string_1error_1state },
    { "string_next_state__native", "(J)Ljava/lang/String;", (void*)::javaproxy::com::sos::scheduler::kernel::core::cppproxy::string_1next_1state },
    { "string_order_state__native", "(J)Ljava/lang/String;", (void*)::javaproxy::com::sos::scheduler::kernel::core::cppproxy::string_1order_1state }
};

namespace zschimmer { namespace javabridge { 

    template<> void has_proxy< ::sos::scheduler::order::job_chain::Node >::register_cpp_proxy_class_in_java() {
        Env env;
        Class* cls = has_proxy< ::sos::scheduler::order::job_chain::Node >::proxy_class_factory.clas();
        int ret = env->RegisterNatives(*cls, native_methods, 3);
        if (ret < 0)  env.throw_java("RegisterNatives");
    }

}}
