// $Id$
// ACHTUNG: NICHT AENDERN! DIESE DATEI IST GENERIERT VON files_to_c++.pl



#include "../zschimmer/zschimmer.h"
#include "../zschimmer/embedded_files.h"

const char file_scheduler_xsd[] = 
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "<!-- $Id$ -->\n"
    "\n"
    "<xsd:schema \n"
    "xmlns:xsd          = \"http://www.w3.org/2001/XMLSchema\" \n"
    "elementFormDefault = \"qualified\">\n"
    "\n"
    "<!-- <xsd:key> nicht verwenden, libxslt kann das nicht: \"Internal error: xmlSchemaAreValuesEqual, failed to compare the values.\" -->\n"
    "\n"
    "<xsd:annotation>\n"
    "<xsd:documentation xml:lang=\"de\">\n"
    "$Id$\n"
    "Schema f\xc3" "\xbc" "r die Scheduler-Konfiguration,\n"
    "s.a. http://www.zschimmer.com/sos/scheduler/konfiguration.html.\n"
    "</xsd:documentation>\n"
    "</xsd:annotation>\n"
    "\n"
    "\n"
    "<xsd:element name=\"spooler\">\n"
    "<xsd:complexType>\n"
    "<xsd:choice>\n"
    "<xsd:element name=\"config\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"base\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"file\" type=\"File\" use=\"required\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element ref=\"security\"         minOccurs=\"0\"/>\n"
    "<xsd:element ref=\"cluster\"          minOccurs=\"0\"/>\n"
    "<xsd:element ref=\"process_classes\"  minOccurs=\"0\"/>\n"
    "<xsd:element ref=\"script\"           minOccurs=\"0\"/>\n"
    "<xsd:element ref=\"web_services\"     minOccurs=\"0\"/>\n"
    "\n"
    "<xsd:choice>\n"
    "<xsd:element ref=\"holidays\"/>\n"
    "<xsd:element ref=\"holiday\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:choice>\n"
    "\n"
    "<xsd:element ref=\"jobs\"             minOccurs=\"0\"/>\n"
    "<xsd:element ref=\"job_chains\"       minOccurs=\"0\"/>\n"
    "<xsd:element ref=\"commands\"         minOccurs=\"0\"/>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"spooler_id\"            type=\"Name\"/>\n"
    "<xsd:attribute name=\"port\"                  type=\"xsd:nonNegativeInteger\"/>\n"
    "<xsd:attribute name=\"tcp_port\"              type=\"xsd:nonNegativeInteger\"/>\n"
    "<xsd:attribute name=\"udp_port\"              type=\"xsd:nonNegativeInteger\"/>\n"
    "<xsd:attribute name=\"ip_address\"            type=\"String\"/>\n"
    "<xsd:attribute name=\"param\"                 type=\"String\"/>\n"
    "<xsd:attribute name=\"log_dir\"               type=\"File\"/>\n"
    "<xsd:attribute name=\"priority_max\"          type=\"xsd:nonNegativeInteger\"/>\n"
    "<xsd:attribute name=\"include_path\"          type=\"File\"/>\n"
    "<xsd:attribute name=\"java_class_path\"       type=\"String\"/>\n"
    "<xsd:attribute name=\"java_options\"          type=\"String\"/>\n"
    "<xsd:attribute name=\"main_scheduler\"        type=\"String\"/>\n"
    "<xsd:attribute name=\"mail_xslt_stylesheet\"  type=\"File\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element ref=\"commands\"/>\n"
    "\n"
    "<xsd:element name=\"command\" type=\"Commands\">\n"
    "<xsd:annotation><xsd:documentation>Deprecated. Use &lt;commands></xsd:documentation></xsd:annotation>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"answer\">\n"
    "<xsd:complexType/>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element ref=\"add_jobs\"/>\n"
    "<xsd:element ref=\"add_order\"/>\n"
    "<xsd:element ref=\"kill_task\"/>\n"
    "<xsd:element ref=\"modify_job\"/>\n"
    "<xsd:element ref=\"modify_order\"/>\n"
    "<xsd:element ref=\"modify_spooler\"/>\n"
    "<xsd:element ref=\"register_remote_scheduler\"/>\n"
    "<xsd:element ref=\"remove_job_chain\"/>\n"
    "<xsd:element ref=\"remove_order\"/>\n"
    "<xsd:element ref=\"run_time\"/>\n"
    "<xsd:element ref=\"show_calendar\"/>\n"
    "<xsd:element ref=\"show_history\"/>\n"
    "<xsd:element ref=\"show_job\"/>\n"
    "<xsd:element ref=\"show_jobs\"/>\n"
    "<xsd:element ref=\"show_job_chains\"/>\n"
    "<xsd:element ref=\"show_job_chain\"/>\n"
    "<xsd:element ref=\"show_order\"/>\n"
    "<xsd:element ref=\"s\"/>\n"
    "<xsd:element ref=\"show_schedulers\"/>\n"
    "<xsd:element ref=\"show_state\"/>\n"
    "<xsd:element ref=\"show_task\"/>\n"
    "<xsd:element ref=\"service_request\"/>\n"
    "<xsd:element ref=\"start_job\"/>\n"
    "<!--xsd:element ref=\"signal_object\"/-->\n"
    "<xsd:element ref=\"terminate\"/>\n"
    "\n"
    "\n"
    "<!-- Asynchron ausgef\xc3" "\xbc" "hrte Kommandos -->\n"
    "<xsd:element ref=\"get_events\"/>\n"
    "</xsd:choice>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"cluster_member_command\">\n"
    "<xsd:complexType>\n"
    "<xsd:choice>\n"
    "<xsd:element name=\"terminate\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"timeout\" type=\"xsd:integer\"/>\n"
    "<xsd:attribute name=\"restart\" type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:choice>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"commands\" type=\"Commands\"/>\n"
    "\n"
    "<xsd:complexType name=\"Commands\">\n"
    "<xsd:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:element ref=\"add_jobs\"/>\n"
    "<xsd:element ref=\"add_order\"/>\n"
    "<xsd:element ref=\"kill_task\"/>\n"
    "<xsd:element ref=\"modify_job\"/>\n"
    "<xsd:element ref=\"modify_order\"/>\n"
    "<xsd:element ref=\"modify_spooler\"/>\n"
    "<xsd:element ref=\"register_remote_scheduler\"/>\n"
    "<xsd:element ref=\"remove_job_chain\"/>\n"
    "<xsd:element ref=\"remove_order\"/>\n"
    "<xsd:element ref=\"run_time\"/>\n"
    "<xsd:element ref=\"show_calendar\"/>\n"
    "<xsd:element ref=\"show_history\"/>\n"
    "<xsd:element ref=\"show_job\"/>\n"
    "<xsd:element ref=\"show_jobs\"/>\n"
    "<xsd:element ref=\"show_job_chains\"/>\n"
    "<xsd:element ref=\"show_job_chain\"/>\n"
    "<xsd:element ref=\"show_order\"/>\n"
    "<xsd:element ref=\"s\"/>\n"
    "<xsd:element ref=\"show_schedulers\"/>\n"
    "<xsd:element ref=\"show_state\"/>\n"
    "<xsd:element ref=\"show_task\"/>\n"
    "<xsd:element ref=\"service_request\"/>\n"
    "<xsd:element ref=\"start_job\"/>\n"
    "<!--xsd:element ref=\"signal_object\"/-->\n"
    "<xsd:element ref=\"terminate\"/>\n"
    "</xsd:choice>\n"
    "\n"
    "<xsd:attribute name=\"on_exit_code\">\n"
    "<xsd:annotation>\n"
    "<xsd:documentation>\n"
    "Only valid in element job!\n"
    "examples: on_exit_code=\"success\" on_exit_code=\"error\" on_exit_code=\"1 2 3\"\n"
    "</xsd:documentation>\n"
    "</xsd:annotation>\n"
    "<xsd:simpleType>\n"
    "<xsd:union>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:NMTOKEN\">\n"
    "<xsd:enumeration value=\"success\">\n"
    "<xsd:annotation>\n"
    "<xsd:documentation>This is exit code 0</xsd:documentation>\n"
    "</xsd:annotation>\n"
    "</xsd:enumeration>\n"
    "<xsd:enumeration value=\"error\">\n"
    "<xsd:annotation>\n"
    "<xsd:documentation>This is all other exit codes but 0</xsd:documentation>\n"
    "</xsd:annotation>\n"
    "</xsd:enumeration>\n"
    "<xsd:enumeration value=\"signal\">\n"
    "<xsd:annotation>\n"
    "<xsd:documentation>exit codes less than 0 (a signal under Unix)</xsd:documentation>\n"
    "</xsd:annotation>\n"
    "</xsd:enumeration>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "<xsd:simpleType>\n"
    "<xsd:list>  \n"
    "<xsd:simpleType>\n"
    "<xsd:union>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:integer\"/>\n"
    "</xsd:simpleType>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"Unix_signal_name\"/>\n"
    "</xsd:simpleType>\n"
    "</xsd:union>\n"
    "</xsd:simpleType>\n"
    "</xsd:list>\n"
    "</xsd:simpleType>\n"
    "</xsd:union>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "</xsd:complexType>\n"
    "\n"
    "\n"
    "<xsd:element name=\"add_jobs\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"job\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"add_order\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"params\" minOccurs=\"0\"/>\n"
    "<xsd:element ref=\"run_time\" minOccurs=\"0\"/>\n"
    "\n"
    "<xsd:element name=\"payload\" minOccurs=\"0\">\n"
    "<!--xsd:element ref=\"params\" minOccurs=\"0\"/-->\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:any processContents=\"skip\"/>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"xml_payload\" minOccurs=\"0\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:any processContents=\"skip\"/>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"job_chain\"         type=\"Name\"         use=\"required\"/>\n"
    "<xsd:attribute name=\"id\"                type=\"Order_id\"/>\n"
    "<xsd:attribute name=\"priority\"          type=\"xsd:integer\"/>\n"
    "<xsd:attribute name=\"title\"             type=\"String\"/>\n"
    "<xsd:attribute name=\"state\"             type=\"String\"/>\n"
    "<xsd:attribute name=\"job\"               type=\"Name\"/>\n"
    "<xsd:attribute name=\"web_service\"       type=\"Name\"/>\n"
    "<xsd:attribute name=\"replace\"           type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"at\"                type=\"Date_time_with_now\"/>\n"
    "<xsd:attribute name=\"suspended\"         type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"holiday\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"date\" type=\"String\" use=\"required\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"holidays\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:element ref=\"holiday\"/>\n"
    "<xsd:element ref=\"include\"/>\n"
    "</xsd:choice>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"include\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"file\" type=\"File\" use=\"required\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"job\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"description\" minOccurs=\"0\">\n"
    "<xsd:complexType mixed=\"true\">\n"
    "<xsd:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:element ref=\"include\"/>\n"
    "</xsd:choice>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element ref=\"params\" minOccurs=\"0\"/>\n"
    "\n"
    "<xsd:choice minOccurs=\"0\">\n"
    "<xsd:element ref=\"script\"/>\n"
    "\n"
    "<xsd:element name=\"process\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"environment\" minOccurs=\"0\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"variable\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"name\"  type=\"String\" use=\"required\"/>\n"
    "<xsd:attribute name=\"value\" type=\"String\" use=\"required\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"file\"              type=\"File\"        use=\"required\"/>\n"
    "<xsd:attribute name=\"param\"             type=\"String\"/>\n"
    "<xsd:attribute name=\"log_file\"          type=\"File\"/>\n"
    "<xsd:attribute name=\"ignore_error\"      type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"ignore_signal\"     type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:choice>\n"
    "\n"
    "<xsd:element name=\"monitor\" minOccurs=\"0\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"script\"/>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"start_when_directory_changed\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"directory\"     type=\"File\"                 use=\"required\"/>\n"
    "<xsd:attribute name=\"regex\"         type=\"String\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"delay_after_error\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"error_count\"   type=\"xsd:positiveInteger\"  use=\"required\"/>\n"
    "<xsd:attribute name=\"delay\"         use=\"required\">\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"String\"/>\n"
    "<!-- Das l\xc3" "\xa4" "sst libxslt abst\xc3" "\xbc" "rzen: \n"
    "<xsd:union>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"Duration\"/>\n"
    "</xsd:simpleType>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:NMTOKEN\">\n"
    "<xsd:enumeration value=\"stop\"/>\n"
    "<xsd:enumeration value=\"stop\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "</xsd:union-->\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"delay_order_after_setback\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"setback_count\" type=\"xsd:positiveInteger\"  use=\"required\"/>\n"
    "<xsd:attribute name=\"delay\"         type=\"Duration\"/>\n"
    "<xsd:attribute name=\"is_maximum\"    type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element ref=\"run_time\" minOccurs=\"0\"/>\n"
    "\n"
    "<xsd:element name=\"commands\" type=\"Commands\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"name\"                  type=\"Name\"             use=\"required\"/>\n"
    "<xsd:attribute name=\"visible\"               type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"priority\"              type=\"Process_priority\"/>\n"
    "<xsd:attribute name=\"temporary\"             type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"spooler_id\"            type=\"Name\"/>\n"
    "<xsd:attribute name=\"title\"                 type=\"String\"/>\n"
    "<xsd:attribute name=\"log_append\"            type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"order\"                 type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"separate_process\"      type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"tasks\"                 type=\"xsd:nonNegativeInteger\"/>\n"
    "<xsd:attribute name=\"min_tasks\"             type=\"xsd:positiveInteger\"/>\n"
    "<xsd:attribute name=\"timeout\"               type=\"Duration\"/>                   <!-- F\xc3" "\xbc" "r ap, 1.4.06 timeout=\"0\" soll erlaubt sein (kein Aprilscherz) -->\n"
    "<xsd:attribute name=\"idle_timeout\"          type=\"Duration\"/>\n"
    "<xsd:attribute name=\"force_idle_timeout\"    type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"process_class\"         type=\"Name\"/>\n"
    "<xsd:attribute name=\"mail_xslt_stylesheet\"  type=\"File\"/>\n"
    "<xsd:attribute name=\"java_options\"          type=\"String\"/>\n"
    "<xsd:attribute name=\"stop_on_error\"         type=\"Yes_no\"/>\n"
    "\n"
    "<xsd:attribute name=\"ignore_signals\">\n"
    "<xsd:simpleType>\n"
    "<xsd:union>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:NMTOKEN\">\n"
    "<xsd:enumeration value=\"all\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "<xsd:simpleType>\n"
    "<xsd:list itemType=\"Unix_signal\"/>\n"
    "</xsd:simpleType>\n"
    "</xsd:union>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "\n"
    "<xsd:attribute name=\"replace\"               type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "\n"
    "<!--libxslt xsd:key name=\"delay_after_error\">\n"
    "<xsd:selector xpath=\"delay_after_error\"/>\n"
    "<xsd:field xpath=\"@error_count\"/>\n"
    "</xsd:key-->\n"
    "\n"
    "<!--libxslt xsd:key name=\"delay_order_after_setback\">\n"
    "<xsd:selector xpath=\"delay_order_after_setback\"/>\n"
    "<xsd:field xpath=\"@setback_count\"/>\n"
    "</xsd:key-->\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"job_chain\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"note\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "\n"
    "<xsd:element name=\"file_order_source\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"directory\"         type=\"String\" use=\"required\"/>\n"
    "<xsd:attribute name=\"regex\"             type=\"Name\"/>\n"
    "<xsd:attribute name=\"delay_after_error\" type=\"xsd:positiveInteger\"/>\n"
    "\n"
    "<xsd:attribute name=\"repeat\">\n"
    "<xsd:simpleType>\n"
    "<xsd:union>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:NMTOKEN\">\n"
    "<xsd:enumeration value=\"no\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:positiveInteger\"/>\n"
    "</xsd:simpleType>\n"
    "</xsd:union>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "\n"
    "<xsd:attribute name=\"max\"               type=\"xsd:positiveInteger\"/>\n"
    "<xsd:attribute name=\"next_state\"        type=\"String\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:choice maxOccurs=\"unbounded\">\n"
    "<xsd:element name=\"job_chain_node\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"state\"         type=\"String\" use=\"required\"/>\n"
    "<xsd:attribute name=\"job\"           type=\"Name\"/>\n"
    "<xsd:attribute name=\"next_state\"    type=\"String\"/>\n"
    "<xsd:attribute name=\"error_state\"   type=\"String\"/>\n"
    "<xsd:attribute name=\"suspend\"       type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "<xsd:element name=\"file_order_sink\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"state\"         type=\"String\" use=\"required\"/>\n"
    "<xsd:attribute name=\"remove\"        type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"move_to\"       type=\"File\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:choice>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"name\"               type=\"Name\"     use=\"required\"/>\n"
    "<xsd:attribute name=\"visible\"            type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"orders_recoverable\" type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"distributed\"        type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "\n"
    "<!--libxslt xsd:key name=\"job_chain_node\">\n"
    "<xsd:selector xpath=\"job_chain_node\"/>\n"
    "<xsd:field xpath=\"@state\"/>\n"
    "</xsd:key-->\n"
    "\n"
    "<!--xsd:keyref name=\"job_chain_node.next_state\" refer=\"job_chain_node\">\n"
    "<xsd:selector xpath=\"job_chain_node\"/>\n"
    "<xsd:field xpath=\"@next_state\"/>\n"
    "</xsd:keyref-->\n"
    "\n"
    "<!--xsd:keyref name=\"job_chain_node.error_state\" refer=\"job_chain_node\">\n"
    "<xsd:selector xpath=\"job_chain_node\"/>\n"
    "<xsd:field xpath=\"@error_state\"/>\n"
    "</xsd:keyref-->\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"job_chains\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"job_chain\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"jobs\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"job\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:sequence>\n"
    "\n"
    "</xsd:complexType>\n"
    "\n"
    "<!--libxslt xsd:key name=\"job\">\n"
    "<xsd:selector xpath=\"job\"/>\n"
    "<xsd:field xpath=\"@name\"/>\n"
    "</xsd:key-->\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"kill_task\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"job\"           type=\"Name\"         use=\"required\"/>\n"
    "<xsd:attribute name=\"id\"            type=\"Task_id\"      use=\"required\"/>\n"
    "<xsd:attribute name=\"immediately\"   type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"modify_job\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"run_time\" minOccurs=\"0\"/>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"job\" type=\"Name\" use=\"required\"/>\n"
    "\n"
    "<xsd:attribute name=\"cmd\">\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:NMTOKEN\">\n"
    "<xsd:enumeration value=\"stop\"/>\n"
    "<xsd:enumeration value=\"unstop\"/>\n"
    "<xsd:enumeration value=\"start\"/>\n"
    "<xsd:enumeration value=\"wake\"/>\n"
    "<xsd:enumeration value=\"end\"/>\n"
    "<xsd:enumeration value=\"suspend\"/>\n"
    "<xsd:enumeration value=\"continue\"/>\n"
    "<xsd:enumeration value=\"reread\"/>\n"
    "<xsd:enumeration value=\"remove\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"modify_order\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"run_time\" minOccurs=\"0\"/>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"job_chain\" type=\"Name\"         use=\"required\"/>\n"
    "<xsd:attribute name=\"order\"     type=\"Order_id\"     use=\"required\"/>\n"
    "<xsd:attribute name=\"priority\"  type=\"xsd:integer\"/>\n"
    "<xsd:attribute name=\"state\"     type=\"String\"/>\n"
    "<xsd:attribute name=\"setback\"   type=\"No\"/>\n"
    "<xsd:attribute name=\"suspended\" type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"modify_spooler\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"cmd\">\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:NMTOKEN\">\n"
    "<xsd:enumeration value=\"pause\"/>\n"
    "<xsd:enumeration value=\"continue\"/>\n"
    "<xsd:enumeration value=\"stop\"/>\n"
    "<xsd:enumeration value=\"reload\"/>\n"
    "<xsd:enumeration value=\"terminate\"/>\n"
    "<xsd:enumeration value=\"terminate_and_restart\"/>\n"
    "<xsd:enumeration value=\"let_run_terminate_and_restart\"/>\n"
    "<xsd:enumeration value=\"abort_immediately\"/>\n"
    "<xsd:enumeration value=\"abort_immediately_and_restart\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "\n"
    "<xsd:attribute name=\"timeout\" type=\"xsd:nonNegativeInteger\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"note\">\n"
    "<xsd:annotation>\n"
    "<xsd:documentation>additional note in HTML</xsd:documentation>\n"
    "</xsd:annotation>\n"
    "<xsd:complexType mixed=\"true\">\n"
    "<xsd:complexContent mixed=\"true\">\n"
    "<xsd:restriction base=\"xsd:anyType\">\n"
    "<xsd:sequence>\n"
    "<xsd:any namespace=\"http://www.w3.org/1999/xhtml\" processContents=\"lax\"/>\n"
    "</xsd:sequence>\n"
    "<xsd:attribute name=\"language\" use=\"required\">\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:string\">\n"
    "<xsd:length value=\"2\"/>\n"
    "<xsd:enumeration value=\"de\"/>\n"
    "<xsd:enumeration value=\"en\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "</xsd:restriction>\n"
    "</xsd:complexContent>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"params\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:choice  minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:element name=\"param\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"name\"  type=\"String\" use=\"required\"/>\n"
    "<xsd:attribute name=\"value\" type=\"String\" use=\"required\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"copy_params\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"from\"  use=\"required\">\n"
    "<xsd:annotation>\n"
    "<xsd:documentation>Only valid in element job/commands/start_job and job/commands/add_order</xsd:documentation>\n"
    "</xsd:annotation>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:NMTOKEN\">\n"
    "<xsd:enumeration value=\"task\"/>\n"
    "<xsd:enumeration value=\"order\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:choice>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"period\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"single_start\"  type=\"Time_of_day\"/>\n"
    "<xsd:attribute name=\"begin\"         type=\"Time_of_day\"/>\n"
    "<xsd:attribute name=\"end\"           type=\"Time_of_day\"/>\n"
    "<xsd:attribute name=\"let_run\"       type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"repeat\"        type=\"Duration\"/>\n"
    "<xsd:attribute name=\"start_once\"    type=\"Yes_no\" default=\"no\">\n"
    "<xsd:annotation>\n"
    "<xsd:documentation>Test only for Joacim Zschimmer</xsd:documentation>\n"
    "</xsd:annotation>\n"
    "</xsd:attribute>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"process_classes\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"process_class\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"name\"              type=\"Name\"/>\n"
    "<xsd:attribute name=\"max_processes\"     type=\"xsd:nonNegativeInteger\"/>\n"
    "<xsd:attribute name=\"spooler_id\"        type=\"Name\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:sequence>\n"
    "<xsd:attribute name=\"ignore\"        type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "\n"
    "<!-- XML-Schema erlaubt keine leeren Schl\xc3" "\xbc" "ssel.\n"
    "<xsd:key name=\"process_class\">\n"
    "<xsd:selector xpath=\"process_class\"/>\n"
    "<xsd:field xpath=\"@name\"/>\n"
    "</xsd:key-->\n"
    "\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"register_remote_scheduler\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"ERROR\" minOccurs=\"0\">\n"
    "<xsd:complexType/>\n"
    "</xsd:element>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"version\"       type=\"String\"/>\n"
    "<xsd:attribute name=\"scheduler_id\"  type=\"String\"/>\n"
    "<xsd:attribute name=\"tcp_port\"      type=\"xsd:nonNegativeInteger\"/>\n"
    "<xsd:attribute name=\"logoff\"        type=\"Yes_no\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"remove_job_chain\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"job_chain\"     type=\"Name\" use=\"required\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"remove_order\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"job_chain\"     type=\"Name\"         use=\"required\"/>\n"
    "<xsd:attribute name=\"order\"         type=\"Order_id\"     use=\"required\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "\n"
    "<xsd:element name=\"run_time\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"period\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "\n"
    "<xsd:element name=\"at\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:attribute name=\"at\" type=\"Date_time\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"date\" minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"period\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:sequence>\n"
    "<xsd:attribute name=\"date\" type=\"String\" use=\"required\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"weekdays\" minOccurs=\"0\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"day\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"period\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:sequence>\n"
    "<xsd:attribute name=\"day\" use=\"required\" type=\"Weekday\"/>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "\n"
    "<!--libxslt xsd:key name=\"weekdays\">\n"
    "<xsd:selector xpath=\"day\"/>\n"
    "<xsd:field xpath=\"@day\"/>\n"
    "</xsd:key-->\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"monthdays\" minOccurs=\"0\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence maxOccurs=\"unbounded\">\n"
    "<xsd:choice>\n"
    "<xsd:element name=\"day\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"period\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"day\" use=\"required\">\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:positiveInteger\">\n"
    "<xsd:maxInclusive value=\"31\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"weekday\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"period\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"day\" use=\"required\" type=\"Weekday\"/>\n"
    "\n"
    "<xsd:attribute name=\"which\" use=\"required\">\n"
    "<xsd:simpleType>\n"
    "<xsd:union>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:positiveInteger\">\n"
    "<xsd:maxInclusive value=\"4\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:negativeInteger\">\n"
    "<xsd:minInclusive value=\"-4\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "</xsd:union>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:choice>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "\n"
    "<!--libxslt xsd:key name=\"monthdays\">\n"
    "<xsd:selector xpath=\"day\"/>\n"
    "<xsd:field xpath=\"@day\"/>\n"
    "</xsd:key-->\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:element name=\"ultimos\" minOccurs=\"0\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element name=\"day\" maxOccurs=\"unbounded\">\n"
    "<xsd:complexType>\n"
    "<xsd:sequence>\n"
    "<xsd:element ref=\"period\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"day\" use=\"required\">\n"
    "<xsd:simpleType>\n"
    "<xsd:restriction base=\"xsd:nonNegativeInteger\">\n"
    "<xsd:maxInclusive value=\"30\"/>\n"
    "</xsd:restriction>\n"
    "</xsd:simpleType>\n"
    "</xsd:attribute>\n"
    "</xsd:complexType>\n"
    "</xsd:element>\n"
    "</xsd:sequence>\n"
    "</xsd:complexType>\n"
    "\n"
    "<!--libxslt xsd:key name=\"ultimos\">\n"
    "<xsd:selector xpath=\"day\"/>\n"
    "<xsd:field xpath=\"@day\"/>\n"
    "</xsd:key-->\n"
    "</xsd:element>\n"
    "\n"
    "<xsd:choice>\n"
    "<xsd:element ref=\"holidays\"/>\n"
    "<xsd:element ref=\"holiday\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
    "</xsd:choice>\n"
    "</xsd:sequence>\n"
    "\n"
    "<xsd:attribute name=\"single_start\"      type=\"Time_of_day\"/>\n"
    "<xsd:attribute name=\"begin\"             type=\"Time_of_day\"/>\n"
    "<xsd:attribute name=\"end\"               type=\"Time_of_day\"/>\n"
    "<xsd:attribute name=\"let_run\"           type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"repeat\"            type=\"Duration\"/>\n"
    "<xsd:attribute name=\"once\"              type=\"Yes_no\"/>\n"
    "<xsd:attribute name=\"start_time_function\" type=\"xsd:NMTOKEN\"/>\n"
    "</xsd:complexType>\n"
    "\n"
    "<!--libxslt xsd:key name=\"at\">\n"
    "<xsd:selector xpath=\"at\"/>\n"
   