#! /bin/bash
set -e

# Origin: https://stackoverflow.com/questions/17695297/importing-the-private-key-public-certificate-pair-in-the-java-keystore
# This script file is expected in src/main/scripts.

cd "$(dirname "$0")/../../../src/test/resources/com/sos/scheduler/engine/agent/client/main"
if [ -d tmp ]; then
  rm --force tmp/*
  rmdir tmp
fi
mkdir tmp

javaKeyStore="test-keystore.jks"
rm --force $javaKeyStore

echo "-- Generate key with AES256"
openssl genrsa -aes256 \
  -out tmp/test-server.key \
  -passout "pass:test-server.key" \
  1024

echo "-- Generate certificate request for CA"
openssl req -batch -x509 -sha256 -new \
  -key tmp/test-server.key \
  -passin "pass:test-server.key" \
  -out tmp/test-server.csr

echo "-- Generate self-signed certificate, valid for 10 years"
openssl x509 -sha256 \
  -days 3652 \
  -in tmp/test-server.csr \
  -signkey tmp/test-server.key \
  -passin "pass:test-server.key" \
  -out tmp/test-selfsigned.crt

echo "-- Create PKCS12 keystore from private key and public certificate"
openssl pkcs12 -export \
  -in tmp/test-selfsigned.crt \
  -inkey tmp/test-server.key \
  -passin "pass:test-server.key" \
  -name test-ssl-server-certificate \
  -out tmp/test-keystore.p12 \
  -passout "pass:test-keystore.p12"

echo "-- Convert PKCS12 keystore into a JKS keystore"
keytool -importkeystore -noprompt \
  -srcstoretype pkcs12 \
  -srckeystore tmp/test-keystore.p12 \
  -alias test-ssl-server-certificate \
  -srcstorepass "test-keystore.p12" \
  -destkeystore test-keystore.jks \
  -deststorepass "test-keystore.jks"
rm -v tmp/test-server.key tmp/test-server.csr tmp/test-selfsigned.crt tmp/test-keystore.p12

keytool -list -keystore "$javaKeyStore" -deststorepass "test-keystore.jks"
echo $(readlink --canonicalize $javaKeyStore)
