#! /bin/bash
# Generates a test TLS certificate
set -e

cd "$(dirname "$0")/../../../src/test/resources/com/sos/scheduler/engine/agent/client/main"

javaKeyStore="https.jks"
rm -v --force $javaKeyStore

keytool -genkey \
  -alias test-ssl-server-certificate \
  -keyalg RSA \
  -keysize 1024 \
  -dname "CN=localhost, O=localhost, OU=Test" \
  -validity 3660 \
  -keypass "https.p12" \
  -storepass "https.jks" \
  -keystore "$javaKeyStore"

keytool -list -keystore "$javaKeyStore" -deststorepass "https.jks"
echo $(readlink --canonicalize $javaKeyStore)
