#! /bin/bash
set -e

cd "$(dirname "$0")/../../../src/test/resources/com/sos/scheduler/engine/agent/client/main"

javaKeyStore="test-keystore.jks"
rm --force $javaKeyStore

keytool -genkey \
  -alias test-ssl-server-certificate \
  -keyalg RSA \
  -keysize 1024 \
  -dname "CN=localhost, O=localhost, OU=Test" \
  -validity 3660 \
  -keypass "test-keystore.p12" \
  -storepass "test-keystore.jks" \
  -keystore "$javaKeyStore"

keytool -list -keystore "$javaKeyStore" -deststorepass "test-keystore.jks"
echo $(readlink --canonicalize $javaKeyStore)
