#!/bin/sh
# $Id: adjust-mod 11348 2005-03-24 10:17:34Z jz $

# Folgendes ist auszuführen mit Root-Rechten im e-Verzeichnis
# chown -R sos *
# chgrp -R sos-e *
# /usr/local/bin/find . -type d -exec chmod g+s {} \;

/usr/local/bin/find . ! -group sos-e -exec chgrp sos-e {} \; , \
  -type f -and \( -perm -100 -and ! -perm -010 -exec chmod g+x {} \; , \
                  -perm -200 -and ! -perm -020 -exec chmod g+w {} \; , \
                  -perm -400 -and ! -perm -040 -exec chmod g+r {} \; \)
