// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_FOLDER_EVENT_FILEBASEDACTIVATEDEVENT_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_FOLDER_EVENT_FILEBASEDACTIVATEDEVENT_H_

#include "com__sos__scheduler__engine__eventbus__AbstractEvent.h"
#include "com__sos__scheduler__engine__kernel__event__ObjectEvent.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace event { struct ObjectEvent; }}}}}}}
namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace folder { struct FileBased; }}}}}}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace folder { namespace event { 


struct FileBasedActivatedEvent__class;

struct FileBasedActivatedEvent : ::zschimmer::javabridge::proxy_jobject< FileBasedActivatedEvent >, ::javaproxy::com::sos::scheduler::engine::kernel::event::ObjectEvent {
    static FileBasedActivatedEvent new_instance(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::kernel::folder::FileBased >& p0);

    FileBasedActivatedEvent(jobject = NULL);

    FileBasedActivatedEvent(const FileBasedActivatedEvent&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        FileBasedActivatedEvent(FileBasedActivatedEvent&&);
    #endif

    ~FileBasedActivatedEvent();

    FileBasedActivatedEvent& operator=(jobject jo) { assign_(jo); return *this; }
    FileBasedActivatedEvent& operator=(const FileBasedActivatedEvent& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        FileBasedActivatedEvent& operator=(FileBasedActivatedEvent&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< FileBasedActivatedEvent >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< FileBasedActivatedEvent >::set_jobject(jo);
        ::javaproxy::com::sos::scheduler::engine::kernel::event::ObjectEvent::set_jobject(jo);
    }
  public:


    ::zschimmer::javabridge::Class* java_object_class_();

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<FileBasedActivatedEvent__class*> {
        void initialize();
    };

    Lazy_class _class;
};


}}}}}}}}

#endif
