// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__Platform.h"
#include "java__lang__Object.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { 

struct Platform__class : ::zschimmer::javabridge::Class
{
    Platform__class(const string& class_name);
   ~Platform__class();


    static const ::zschimmer::javabridge::class_factory< Platform__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< Platform__class > Platform__class::class_factory ("com.sos.scheduler.engine.kernel.Platform");

Platform__class::Platform__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
{}

Platform__class::~Platform__class() {}




Platform::Platform(jobject jo) { if (jo) assign_(jo); }

Platform::Platform(const Platform& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    Platform::Platform(Platform&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

Platform::~Platform() { assign_(NULL); }





::zschimmer::javabridge::Class* Platform::java_object_class_() { return _class.get(); }

::zschimmer::javabridge::Class* Platform::java_class_() { return Platform__class::class_factory.clas(); }


void Platform::Lazy_class::initialize() {
    _value = Platform__class::class_factory.clas();
}


}}}}}}
