// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_JOB_EVENTS_UNMODIFIABLETASKEVENT_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_JOB_EVENTS_UNMODIFIABLETASKEVENT_H_

#include "com__sos__scheduler__engine__kernel__event__AbstractEvent.h"
#include "com__sos__scheduler__engine__kernel__event__Event.h"
#include "com__sos__scheduler__engine__kernel__event__ObjectEvent.h"
#include "com__sos__scheduler__engine__kernel__job__events__TaskEvent.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace job { namespace events { struct TaskEvent; }}}}}}}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace job { namespace events { 


struct UnmodifiableTaskEvent__class;

struct UnmodifiableTaskEvent : ::zschimmer::javabridge::proxy_jobject< UnmodifiableTaskEvent >, ::javaproxy::com::sos::scheduler::engine::kernel::job::events::TaskEvent {
  private:
    static UnmodifiableTaskEvent new_instance();  // Not implemented
  public:

    UnmodifiableTaskEvent(jobject = NULL);

    UnmodifiableTaskEvent(const UnmodifiableTaskEvent&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        UnmodifiableTaskEvent(UnmodifiableTaskEvent&&);
    #endif

    ~UnmodifiableTaskEvent();

    UnmodifiableTaskEvent& operator=(jobject jo) { assign_(jo); return *this; }
    UnmodifiableTaskEvent& operator=(const UnmodifiableTaskEvent& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        UnmodifiableTaskEvent& operator=(UnmodifiableTaskEvent&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< UnmodifiableTaskEvent >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< UnmodifiableTaskEvent >::set_jobject(jo);
        ::javaproxy::com::sos::scheduler::engine::kernel::job::events::TaskEvent::set_jobject(jo);
    }
  public:


    ::zschimmer::javabridge::Class* java_object_class_();

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<UnmodifiableTaskEvent__class*> {
        void initialize();
    };

    Lazy_class _class;
};


}}}}}}}}

#endif
