// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__order__UnmodifiableOrder.h"
#include "com__sos__scheduler__engine__kernel__order__OrderId.h"
#include "com__sos__scheduler__engine__kernel__order__OrderState.h"
#include "java__lang__Object.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { 

struct UnmodifiableOrder__class : ::zschimmer::javabridge::Class
{
    UnmodifiableOrder__class(const string& class_name);
   ~UnmodifiableOrder__class();

    ::zschimmer::javabridge::Method const _getEndState____method;
    ::zschimmer::javabridge::Method const _getId____method;
    ::zschimmer::javabridge::Method const _getState____method;
    ::zschimmer::javabridge::Method const _getTitle____method;

    static const ::zschimmer::javabridge::class_factory< UnmodifiableOrder__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< UnmodifiableOrder__class > UnmodifiableOrder__class::class_factory ("com.sos.scheduler.engine.kernel.order.UnmodifiableOrder");

UnmodifiableOrder__class::UnmodifiableOrder__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
    ,_getEndState____method(this, "getEndState", "()Lcom/sos/scheduler/engine/kernel/order/OrderState;")
    ,_getId____method(this, "getId", "()Lcom/sos/scheduler/engine/kernel/order/OrderId;")
    ,_getState____method(this, "getState", "()Lcom/sos/scheduler/engine/kernel/order/OrderState;")
    ,_getTitle____method(this, "getTitle", "()Ljava/lang/String;"){}

UnmodifiableOrder__class::~UnmodifiableOrder__class() {}




UnmodifiableOrder::UnmodifiableOrder(jobject jo) { if (jo) assign_(jo); }

UnmodifiableOrder::UnmodifiableOrder(const UnmodifiableOrder& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    UnmodifiableOrder::UnmodifiableOrder(UnmodifiableOrder&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

UnmodifiableOrder::~UnmodifiableOrder() { assign_(NULL); }




::javaproxy::com::sos::scheduler::engine::kernel::order::OrderState UnmodifiableOrder::getEndState() {
    ::zschimmer::javabridge::raw_parameter_list<0> parameter_list;
    UnmodifiableOrder__class* cls = _class.get();
    ::javaproxy::com::sos::scheduler::engine::kernel::order::OrderState result;
    result.steal_local_ref(cls->_getEndState____method.jobject_call(get_jobject(), parameter_list));
    return result;
}

::javaproxy::com::sos::scheduler::engine::kernel::order::OrderId UnmodifiableOrder::getId() {
    ::zschimmer::javabridge::raw_parameter_list<0> parameter_list;
    UnmodifiableOrder__class* cls = _class.get();
    ::javaproxy::com::sos::scheduler::engine::kernel::order::OrderId result;
    result.steal_local_ref(cls->_getId____method.jobject_call(get_jobject(), parameter_list));
    return result;
}

::javaproxy::com::sos::scheduler::engine::kernel::order::OrderState UnmodifiableOrder::getState() {
    ::zschimmer::javabridge::raw_parameter_list<0> parameter_list;
    UnmodifiableOrder__class* cls = _class.get();
    ::javaproxy::com::sos::scheduler::engine::kernel::order::OrderState result;
    result.steal_local_ref(cls->_getState____method.jobject_call(get_jobject(), parameter_list));
    return result;
}

::javaproxy::java::lang::String UnmodifiableOrder::getTitle() {
    ::zschimmer::javabridge::raw_parameter_list<0> parameter_list;
    UnmodifiableOrder__class* cls = _class.get();
    ::javaproxy::java::lang::String result;
    result.steal_local_ref(cls->_getTitle____method.jobject_call(get_jobject(), parameter_list));
    return result;
}


::zschimmer::javabridge::Class* UnmodifiableOrder::java_object_class_() { return _class.get(); }

::zschimmer::javabridge::Class* UnmodifiableOrder::java_class_() { return UnmodifiableOrder__class::class_factory.clas(); }


void UnmodifiableOrder::Lazy_class::initialize() {
    _value = UnmodifiableOrder__class::class_factory.clas();
}


}}}}}}}
