// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__cppproxy__HttpResponseC.h"
#include "com__sos__scheduler__engine__kernel__cppproxy__HttpChunkReaderC.h"
#include "java__lang__Object.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace cppproxy { 

struct HttpResponseC__class : ::zschimmer::javabridge::Class
{
    HttpResponseC__class(const string& class_name);
   ~HttpResponseC__class();


    static const ::zschimmer::javabridge::class_factory< HttpResponseC__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< HttpResponseC__class > HttpResponseC__class::class_factory ("com.sos.scheduler.engine.kernel.cppproxy.HttpResponseC");

HttpResponseC__class::HttpResponseC__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
{}

HttpResponseC__class::~HttpResponseC__class() {}




HttpResponseC::HttpResponseC(jobject jo) { if (jo) assign_(jo); }

HttpResponseC::HttpResponseC(const HttpResponseC& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    HttpResponseC::HttpResponseC(HttpResponseC&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

HttpResponseC::~HttpResponseC() { assign_(NULL); }





::zschimmer::javabridge::Class* HttpResponseC::java_object_class_() const { return _class.get(); }

::zschimmer::javabridge::Class* HttpResponseC::java_class_() { return HttpResponseC__class::class_factory.clas(); }


void HttpResponseC::Lazy_class::initialize() const {
    _value = HttpResponseC__class::class_factory.clas();
}


}}}}}}}
