// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__job__events__TaskEndedEvent.h"
#include "com__sos__scheduler__engine__kernel__job__UnmodifiableTask.h"
#include "com__sos__scheduler__engine__kernel__job__events__UnmodifiableTaskEvent.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace job { namespace events { 

struct TaskEndedEvent__class : ::zschimmer::javabridge::Class
{
    TaskEndedEvent__class(const string& class_name);
   ~TaskEndedEvent__class();

    ::zschimmer::javabridge::Method const __constructor__Lcom_sos_scheduler_engine_kernel_job_UnmodifiableTask_2__method;

    static const ::zschimmer::javabridge::class_factory< TaskEndedEvent__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< TaskEndedEvent__class > TaskEndedEvent__class::class_factory ("com.sos.scheduler.engine.kernel.job.events.TaskEndedEvent");

TaskEndedEvent__class::TaskEndedEvent__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
    ,__constructor__Lcom_sos_scheduler_engine_kernel_job_UnmodifiableTask_2__method(this, "<init>", "(Lcom/sos/scheduler/engine/kernel/job/UnmodifiableTask;)V"){}

TaskEndedEvent__class::~TaskEndedEvent__class() {}



TaskEndedEvent TaskEndedEvent::new_instance(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::kernel::job::UnmodifiableTask >& p0) {
    TaskEndedEvent result;
    result.java_object_allocate_();
    ::zschimmer::javabridge::raw_parameter_list<1> parameter_list;
    parameter_list._jvalues[0].l = p0.get_jobject();
    TaskEndedEvent__class* cls = result._class.get();
    cls->__constructor__Lcom_sos_scheduler_engine_kernel_job_UnmodifiableTask_2__method.call(result.get_jobject(), parameter_list);
    return result;
}


TaskEndedEvent::TaskEndedEvent(jobject jo) { if (jo) assign_(jo); }

TaskEndedEvent::TaskEndedEvent(const TaskEndedEvent& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    TaskEndedEvent::TaskEndedEvent(TaskEndedEvent&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

TaskEndedEvent::~TaskEndedEvent() { assign_(NULL); }





::zschimmer::javabridge::Class* TaskEndedEvent::java_object_class_() { return _class.get(); }

::zschimmer::javabridge::Class* TaskEndedEvent::java_class_() { return TaskEndedEvent__class::class_factory.clas(); }


void TaskEndedEvent::Lazy_class::initialize() {
    _value = TaskEndedEvent__class::class_factory.clas();
}


}}}}}}}}
