// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__order__OrderResumedEvent.h"
#include "com__sos__scheduler__engine__kernel__order__UnmodifiableOrder.h"
#include "com__sos__scheduler__engine__kernel__order__UnmodifiableOrderEvent.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { 

struct OrderResumedEvent__class : ::zschimmer::javabridge::Class
{
    OrderResumedEvent__class(const string& class_name);
   ~OrderResumedEvent__class();

    ::zschimmer::javabridge::Method const __constructor__Lcom_sos_scheduler_engine_kernel_order_UnmodifiableOrder_2__method;

    static const ::zschimmer::javabridge::class_factory< OrderResumedEvent__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< OrderResumedEvent__class > OrderResumedEvent__class::class_factory ("com.sos.scheduler.engine.kernel.order.OrderResumedEvent");

OrderResumedEvent__class::OrderResumedEvent__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
    ,__constructor__Lcom_sos_scheduler_engine_kernel_order_UnmodifiableOrder_2__method(this, "<init>", "(Lcom/sos/scheduler/engine/kernel/order/UnmodifiableOrder;)V"){}

OrderResumedEvent__class::~OrderResumedEvent__class() {}



OrderResumedEvent OrderResumedEvent::new_instance(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::kernel::order::UnmodifiableOrder >& p0) {
    OrderResumedEvent result;
    result.java_object_allocate_();
    ::zschimmer::javabridge::raw_parameter_list<1> parameter_list;
    parameter_list._jvalues[0].l = p0.get_jobject();
    OrderResumedEvent__class* cls = result._class.get();
    cls->__constructor__Lcom_sos_scheduler_engine_kernel_order_UnmodifiableOrder_2__method.call(result.get_jobject(), parameter_list);
    return result;
}


OrderResumedEvent::OrderResumedEvent(jobject jo) { if (jo) assign_(jo); }

OrderResumedEvent::OrderResumedEvent(const OrderResumedEvent& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    OrderResumedEvent::OrderResumedEvent(OrderResumedEvent&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

OrderResumedEvent::~OrderResumedEvent() { assign_(NULL); }





::zschimmer::javabridge::Class* OrderResumedEvent::java_object_class_() { return _class.get(); }

::zschimmer::javabridge::Class* OrderResumedEvent::java_class_() { return OrderResumedEvent__class::class_factory.clas(); }


void OrderResumedEvent::Lazy_class::initialize() {
    _value = OrderResumedEvent__class::class_factory.clas();
}


}}}}}}}
