// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_JAVA_UTIL_LIST_H_
#define _JAVAPROXY_JAVA_UTIL_LIST_H_

#include "java__lang__Object.h"

namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace java { namespace util { 


struct List__class;

struct List : ::zschimmer::javabridge::proxy_jobject< List >, ::javaproxy::java::lang::Object {
  private:
    static List new_instance();  // Not implemented
  public:

    List(jobject = NULL);

    List(const List&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        List(List&&);
    #endif

    ~List();

    List& operator=(jobject jo) { assign_(jo); return *this; }
    List& operator=(const List& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        List& operator=(List&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< List >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< List >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    void add(jint p0, const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p1);
    bool add(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p0);
    void clear();
    bool contains(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p0);
    bool equals(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p0);
    ::javaproxy::java::lang::Object get(jint p0);
    jint hashCode();
    jint indexOf(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p0);
    bool isEmpty();
    jint lastIndexOf(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p0);
    ::javaproxy::java::lang::Object remove(jint p0);
    bool remove(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p0);
    ::javaproxy::java::lang::Object set(jint p0, const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::Object >& p1);
    jint size();
    ::javaproxy::java::util::List subList(jint p0, jint p1);

    ::zschimmer::javabridge::Class* java_object_class_();

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<List__class*> {
        void initialize();
    };

    Lazy_class _class;
};


}}}

#endif
