// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_JOBCHAIN_JOBNODE_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_JOBCHAIN_JOBNODE_H_

#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"
#include "com__sos__scheduler__engine__kernel__order__jobchain__Node.h"
#include "com__sos__scheduler__engine__kernel__order__jobchain__OrderQueueNode.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { namespace jobchain { struct OrderQueueNode; }}}}}}}}
namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { struct Order; }}}}}}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}
namespace javaproxy { namespace org { namespace w3c { namespace dom { struct Element; }}}}
namespace javaproxy { namespace scala { struct Option; }}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { namespace jobchain { 


struct JobNode__class;

struct JobNode : ::zschimmer::javabridge::proxy_jobject< JobNode >, ::javaproxy::com::sos::scheduler::engine::kernel::order::jobchain::OrderQueueNode {
    static JobNode new_instance();

    JobNode(jobject = NULL);

    JobNode(const JobNode&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        JobNode(JobNode&&);
    #endif

    ~JobNode();

    JobNode& operator=(jobject jo) { assign_(jo); return *this; }
    JobNode& operator=(const JobNode& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        JobNode& operator=(JobNode&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< JobNode >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< JobNode >::set_jobject(jo);
        ::javaproxy::com::sos::scheduler::engine::kernel::order::jobchain::OrderQueueNode::set_jobject(jo);
    }
  public:

    void onOrderStepEnded(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::com::sos::scheduler::engine::kernel::order::Order >& p0, jint p1) const;
    ::javaproxy::java::lang::String orderStateTransitionToState(jlong p0) const;
    void processConfigurationDomElement(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::org::w3c::dom::Element >& p0) const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<JobNode__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}}}}}

#endif
