// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_DATA_JOB_TASKID_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_DATA_JOB_TASKID_H_

#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace data { namespace job { 


struct TaskId__class;

struct TaskId : ::zschimmer::javabridge::proxy_jobject< TaskId >, ::javaproxy::java::lang::Object {
  private:
    static TaskId new_instance();  // Not implemented
  public:

    TaskId(jobject = NULL);

    TaskId(const TaskId&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        TaskId(TaskId&&);
    #endif

    ~TaskId();

    TaskId& operator=(jobject jo) { assign_(jo); return *this; }
    TaskId& operator=(const TaskId& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        TaskId& operator=(TaskId&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< TaskId >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< TaskId >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    jint number() const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<TaskId__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}}}}

#endif
