// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_JOBCHAIN_JOBCHAIN_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_JOBCHAIN_JOBCHAIN_H_

#include "../zschimmer/zschimmer.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace filebased { struct FileBased; }}}}}}}
namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}
namespace javaproxy { namespace java { namespace util { struct ArrayList; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { namespace jobchain { 


struct JobChain__class;

struct JobChain : ::zschimmer::javabridge::proxy_jobject< JobChain >, ::javaproxy::java::lang::Object {
  private:
    static JobChain new_instance();  // Not implemented
  public:

    JobChain(jobject = NULL);

    JobChain(const JobChain&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        JobChain(JobChain&&);
    #endif

    ~JobChain();

    JobChain& operator=(jobject jo) { assign_(jo); return *this; }
    JobChain& operator=(const JobChain& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        JobChain& operator=(JobChain&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< JobChain >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< JobChain >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:

    ::javaproxy::java::util::ArrayList cppSkippedStates(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0) const;
    void deletePersistentState() const;
    void loadPersistentState() const;
    void onNextStateActionChanged() const;
    void persistState() const;

    ::zschimmer::javabridge::Class* java_object_class_() const;

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<JobChain__class*> {
        void initialize() const;
    };

    Lazy_class _class;
};


}}}}}}}}

#endif
