// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_CPPPROXY_ORDER_QUEUE_NODEC_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_CPPPROXY_ORDER_QUEUE_NODEC_H_

#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace cppproxy { struct Order_queueC; }}}}}}}
namespace javaproxy { namespace java { namespace lang { struct Object; }}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace cppproxy { 


struct Order_queue_nodeC__class;

struct Order_queue_nodeC : ::zschimmer::javabridge::proxy_jobject< Order_queue_nodeC >, ::javaproxy::java::lang::Object {
  private:
    static Order_queue_nodeC new_instance();  // Not implemented
  public:

    Order_queue_nodeC(jobject = NULL);

    Order_queue_nodeC(const Order_queue_nodeC&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Order_queue_nodeC(Order_queue_nodeC&&);
    #endif

    ~Order_queue_nodeC();

    Order_queue_nodeC& operator=(jobject jo) { assign_(jo); return *this; }
    Order_queue_nodeC& operator=(const Order_queue_nodeC& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        Order_queue_nodeC& operator=(Order_queue_nodeC&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< Order_queue_nodeC >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< Order_queue_nodeC >::set_jobject(jo);
        ::javaproxy::java::lang::Object::set_jobject(jo);
    }
  public:


    ::zschimmer::javabridge::Class* java_object_class_();

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<Order_queue_nodeC__class*> {
        void initialize();
    };

    Lazy_class _class;
};


}}}}}}}

#endif
