// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__log__LogEvent.h"
#include "com__sos__scheduler__engine__kernel__event__AbstractEvent.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace log { 

struct LogEvent__class : ::zschimmer::javabridge::Class
{
    LogEvent__class(const string& class_name);
   ~LogEvent__class();

    ::zschimmer::javabridge::Method const __constructor__Ljava_lang_String_2__method;

    static const ::zschimmer::javabridge::class_factory< LogEvent__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< LogEvent__class > LogEvent__class::class_factory ("com.sos.scheduler.engine.kernel.log.LogEvent");

LogEvent__class::LogEvent__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
    ,__constructor__Ljava_lang_String_2__method(this, "<init>", "(Ljava/lang/String;)V"){}

LogEvent__class::~LogEvent__class() {}



LogEvent LogEvent::new_instance(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0) {
    LogEvent result;
    result.java_object_allocate_();
    ::zschimmer::javabridge::raw_parameter_list<1> parameter_list;
    parameter_list._jvalues[0].l = p0.get_jobject();
    LogEvent__class* cls = result._class.get();
    cls->__constructor__Ljava_lang_String_2__method.call(result.get_jobject(), parameter_list);
    return result;
}


LogEvent::LogEvent(jobject jo) { if (jo) assign_(jo); }

LogEvent::LogEvent(const LogEvent& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    LogEvent::LogEvent(LogEvent&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

LogEvent::~LogEvent() { assign_(NULL); }





::zschimmer::javabridge::Class* LogEvent::java_object_class_() { return _class.get(); }

::zschimmer::javabridge::Class* LogEvent::java_class_() { return LogEvent__class::class_factory.clas(); }


void LogEvent::Lazy_class::initialize() {
    _value = LogEvent__class::class_factory.clas();
}


}}}}}}}
