// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#include "com__sos__scheduler__engine__kernel__event__Event.h"
#include "java__lang__Object.h"
#include "java__lang__String.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace event { 

struct Event__class : ::zschimmer::javabridge::Class
{
    Event__class(const string& class_name);
   ~Event__class();

    ::zschimmer::javabridge::Method const __constructor____method;

    static const ::zschimmer::javabridge::class_factory< Event__class > class_factory;
};

const ::zschimmer::javabridge::class_factory< Event__class > Event__class::class_factory ("com.sos.scheduler.engine.kernel.event.Event");

Event__class::Event__class(const string& class_name) :
    ::zschimmer::javabridge::Class(class_name)
    ,__constructor____method(this, "<init>", "()V"){}

Event__class::~Event__class() {}



Event Event::new_instance() {
    Event result;
    result.java_object_allocate_();
    ::zschimmer::javabridge::raw_parameter_list<0> parameter_list;
    Event__class* cls = result._class.get();
    cls->__constructor____method.call(result.get_jobject(), parameter_list);
    return result;
}


Event::Event(jobject jo) { if (jo) assign_(jo); }

Event::Event(const Event& o) { assign_(o.get_jobject()); }

#ifdef Z_HAS_MOVE_CONSTRUCTOR
    Event::Event(Event&& o) { set_jobject(o.get_jobject());  o.set_jobject(NULL); }
#endif

Event::~Event() { assign_(NULL); }





::zschimmer::javabridge::Class* Event::java_object_class_() { return _class.get(); }

::zschimmer::javabridge::Class* Event::java_class_() { return Event__class::class_factory.clas(); }


void Event::Lazy_class::initialize() {
    _value = Event__class::class_factory.clas();
}


}}}}}}}
