package com.sos.scheduler.engine.kernel.eventing;

import sos.spooler.Order;

/**
* \class SchedulerEventListener 
* 
* \brief SchedulerEventListener - 
* 
* \details
*
* \section SchedulerEventListener.java_intro_sec Introduction
*
* \section SchedulerEventListener.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author rb
* \version 16.07.2010
* \see reference
*
* Created on 16.07.2010 08:50:56
 */

public class SchedulerEventListener {

    @SuppressWarnings("unused")
    private final String    conClassName    = "SchedulerEventListener";

    public SchedulerEventListener() {
        
    }
    
//    public void newEvent(String event) 
//    {
//        
//        System.out.println("addEvent:" + event);
//    }
    
    public void newEvent(Object order) 
    {
        Order order1 = (Order)order;
        System.out.println("newEvent, order.title:" + order1.title());
    }

    
    
}
