#! /bin/bash
# $Id$

# Erzeugt die Parameter für ld, um eine Reihe von Symbolen in einem shared object zu exportieren

if [ "`uname`" == "Linux" ]; then

    filename=version_script

    echo "{ global: " >$filename;

    while [ -n "$1" ]; do
        echo "$1;" >>$filename
        shift;
    done;

    echo " local: *; };" >>$filename

    echo "-Wl,--version-script=$filename"

elif [ "`uname`" == "SunOS" ]; then

    filename=version_script

    echo "{ global: " >$filename;

    while [ -n "$1" ]; do
        echo "$1;" >>$filename
        shift;
    done;

    echo " local: *; };" >>$filename

    echo "-Wl,-M -Wl,$filename"

elif [ "`uname`" == "HP-UX" ]; then :

    if [ "`uname -r`" != "B.11.11" ]  ||  [ "$*" != "main" ]; then :
        while [ -n "$1" ]; do
            echo "-Wl,+e,$1"
            shift
        done
    fi

    #if [ "`uname -r`" == "B.11.11" ]; then :  #2008-04-12 Joacim Zschimmer 
    #    echo "-Wl,+e,_end"
    #    echo "-Wl,+e,_curbrk"
    #    echo "-Wl,+e,malloc"
    #fi

else 

    : # ?

fi
