#! /bin/bash
# $Id$

executable="$1"
cp $executable ../../bin/"scheduler.debug"

executable_debug_info="$executable.debug-info"

PATH=/opt/hp-gcc-4.1.1/bin/:$PATH
 
if objcopy --version | grep 'GNU objcopy 2.14' >/dev/null; then :
    cp -p "$executable" "$executable_debug_info"  || exit
    strip "$executable"
else
    objcopy --preserve-dates  --only-keep-debug  "$executable" "$executable_debug_info"  || exit
    objcopy --preserve-dates  --strip-debug  "$executable"  || exit
    objcopy --preserve-dates  --add-gnu-debuglink="$executable_debug_info" "$executable"  || exit
fi

chmod -x "$executable_debug_info"

rm -f "$executable_debug_info.{bz2,lzma}"     # Alte von release erzeugte löschen
#if which lzma &>/dev/null; then :
#    lzma --force "$executable_debug_info"
# else :
#    bzip2 --force "$executable_debug_info"
#fi
