// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "spooler.h"
#include "../zschimmer/java.h"
#include "../zschimmer/Has_proxy.h"
#include "../zschimmer/javaproxy.h"
#include "../zschimmer/lazy.h"

using namespace ::zschimmer;
using namespace ::zschimmer::javabridge;

namespace zschimmer { namespace javabridge { 

    template<> const class_factory<Proxy_class> has_proxy< ::sos::scheduler::Task >::proxy_class_factory("com.sos.scheduler.engine.kernel.cppproxy.TaskCImpl");

}}



namespace zschimmer { namespace javabridge { 

    template<> void has_proxy< ::sos::scheduler::Task >::register_cpp_proxy_class_in_java() {
    }

}}
