// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

#include "_precompiled.h"

#ifndef _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_ORDERID_H_
#define _JAVAPROXY_COM_SOS_SCHEDULER_ENGINE_KERNEL_ORDER_ORDERID_H_

#include "com__sos__scheduler__engine__kernel__util__StringValue.h"
#include "java__lang__Object.h"

namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace util { struct StringValue; }}}}}}}
namespace javaproxy { namespace java { namespace lang { struct String; }}}


namespace javaproxy { namespace com { namespace sos { namespace scheduler { namespace engine { namespace kernel { namespace order { 


struct OrderId__class;

struct OrderId : ::zschimmer::javabridge::proxy_jobject< OrderId >, ::javaproxy::com::sos::scheduler::engine::kernel::util::StringValue {
    static OrderId new_instance(const ::zschimmer::javabridge::proxy_jobject< ::javaproxy::java::lang::String >& p0);

    OrderId(jobject = NULL);

    OrderId(const OrderId&);

    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        OrderId(OrderId&&);
    #endif

    ~OrderId();

    OrderId& operator=(jobject jo) { assign_(jo); return *this; }
    OrderId& operator=(const OrderId& o) { assign_(o.get_jobject()); return *this; }
    #ifdef Z_HAS_MOVE_CONSTRUCTOR
        OrderId& operator=(OrderId&& o) { set_jobject(o.get_jobject()); o.set_jobject(NULL); return *this; }
    #endif

    jobject get_jobject() const { return ::zschimmer::javabridge::proxy_jobject< OrderId >::get_jobject(); }

  protected:
    void set_jobject(jobject jo) {
        ::zschimmer::javabridge::proxy_jobject< OrderId >::set_jobject(jo);
        ::javaproxy::com::sos::scheduler::engine::kernel::util::StringValue::set_jobject(jo);
    }
  public:


    ::zschimmer::javabridge::Class* java_object_class_();

    static ::zschimmer::javabridge::Class* java_class_();


  private:
    struct Lazy_class : ::zschimmer::abstract_lazy<OrderId__class*> {
        void initialize();
    };

    Lazy_class _class;
};


}}}}}}}

#endif
