#! /bin/sh 
# $Id$

echo "date && \
      ( echo 'Batch Job (soscopy/sosfs) gestartet'|/usr/local/samba/bin/smbclient -M $LOGNAME ) ; \
      ( sosmake kram sosarray.o && \
        sosmake kram sosfield.o && \
        sosmake file anyfile.o && \
        sosmake file typefile.o && \
        sosmake kram && \
        sosmake file && \
        sosmake fs && \
        sosmake rapid && \
        sosmake sosingre && \
        sosmake kram soswnmai.o && \
        sosmake fs sosfs && \
        sosmake file hostcopy ) ||\
      ( echo 'Batch Job (soscopy/sosfs) beendet'|/usr/local/samba/bin/smbclient -M $LOGNAME ) "  | batch -sm
