#! /bin/bash
# $Id$

# In misc/microsoft ist eine riesige Word-DLL. Die brauchen wir nur für Windows (und eigentlich nur die TLB).
rsync_options='--exclude microsoft'

[ -z "$*" ]  && subdirs=  ||  subdirs="{${subdirs// /,}}"


[ `whoami` == "root" ]  &&  echo "Skript darf wegen 'rm -rf' nicht als root laufen, zu gefährlich!" && exit 1

tmp=/tmp/`whoami`
[ -d $tmp ] || mkdir $tmp || exit 1

module=$(basename `pwd`)
tmp_module=$tmp/$module
archive=$tmp/$module.tar.bz2


echo Quellen werden nach $tmp_module kopiert ...
rsync -a --cvs-exclude --exclude "*.class" --exclude .svn --delete --force $rsync_options .  $tmp_module/$subdirs

echo "tar prod >$archive ..."
tar cf - -C $tmp  $module  |  bzip2 >$archive  &&  rm -rf $tmp_module/  &&  ls -l $archive


#tar cf - Makefile `find file fs misc e370 factory hostjava hostphp hostole kram make libxml2 rapid spooler zlib zschimmer -type f  ! -name "*.dll"  ! -name "*.doc"  ! -name "*.rtf"  ! -name "*.d"  ! -name "*.so"  ! -name "*.a"  ! -name "*.o"  ! -name "*.class"  ! -name "*.log"  ! -name "*.map"  ! -path "*/CVS*"  ! -name "\\.*"` | bzip2 >e.tar.bz2
