/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sos_Factory_0005fprocessor */

#ifndef _Included_sos_Factory_0005fprocessor
#define _Included_sos_Factory_0005fprocessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    set_language
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sos_Factory_1processor_set_1language
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    language
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sos_Factory_1processor_language
  (JNIEnv *, jobject);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    set_template_filename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sos_Factory_1processor_set_1template_1filename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    template_filename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sos_Factory_1processor_template_1filename
  (JNIEnv *, jobject);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    set_head_filename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sos_Factory_1processor_set_1head_1filename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    head_filename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sos_Factory_1processor_head_1filename
  (JNIEnv *, jobject);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    set_document_filename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sos_Factory_1processor_set_1document_1filename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    document_filename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sos_Factory_1processor_document_1filename
  (JNIEnv *, jobject);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    set_parameter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sos_Factory_1processor_set_1parameter
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    parameter
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sos_Factory_1processor_parameter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    process
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sos_Factory_1processor_process
  (JNIEnv *, jobject);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sos_Factory_1processor_construct
  (JNIEnv *, jobject);

/*
 * Class:     sos_Factory_0005fprocessor
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sos_Factory_1processor_destruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
