// *** Generated by com.sos.scheduler.engine.cplusplus.generator ***

package com.sos.scheduler.engine.kernel.cppproxy;
/** Dummy-Modul für Javadoc, damit es nicht mangels Klasse mit öffentlichem Konstruktor abbricht. */

public final class ZZZJavadocDummy{
    public ZZZJavadocDummy() { throw new UnsupportedOperationException("com.sos.scheduler.engine.kernel.cppproxy.ZZZJavadocDummy"); }
}
