#! /bin/bash
# $Id: start-spooler 11348 2005-03-24 10:17:34Z jz $

# Diese Einstellungen müssen angepasst werden:

spooler=bin/spooler
param="/home/joacim/tmp/java.spooler -service -log-dir=/tmp/spooler"
stderr=/tmp/spooler/stderr

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/j2sdk/jre/lib/i386/client:/opt/j2sdk/jre/lib/i386"

#--------------------------------------------------------------------------------------------------

test -x $spooler || exit 1

case "$1" in

    start)
        $spooler $param &>$stderr
        ;;

    stop)
        $spooler $param -send-cmd='<modify_spooler cmd="terminate"/>'
        ;;

    restart)
        $spooler $param -send-cmd='<modify_spooler cmd="terminate_and_restart"/>'
        ;;

    reload)
        $spooler $param -send-cmd='<modify_spooler cmd="reload"/>'
        ;;

    status)
        $spooler $param -send-cmd='<show_state/>'
        ;;

    *)
        echo "Usage: $0 {start|stop|status|restart|reload}"
        exit 1
        ;;
esac
