#! /bin/bash
# $Id: bin-to-sos 11348 2005-03-24 10:17:34Z jz $
# Kopiert ausgewählte Dateien von bin zur SOS


case `uname` in
    Linux)
        subdir=linux
        ;;

    sunos?)
        subdir=solaris
        ;;

    *)
        echo uname liefert unbekanntes Betriebssystem   
        exit 1
esac

( cd bin && \
  files=`echo hostcopy \
              spooler \
              hostjava.jar \
              sos.*.jar \
              ../hostphp/{hostphp,hostware_file,hostware_dynobj}.inc \
              ../spooler/spooler.dtd \
              libsosperlscript.so \
              libhostphp-*.so \
              libhostjava.so` &&
  cmd="rsync -zv --progress $files cvs.sos:/home/sos/jz/$subdir/"
  echo $cmd
  $cmd
)
