#! /bin/bash

# Unter Windows muss Umgebungsvariable WINDOWS_NET_SDK_HOME den Installationpfad des Micosoft Windows SDK (.Net-SDK) enthalten,
# zum Beispiel: set WINDOWS_NET_SDK_HOME=%windir%\Microsoft.NET\Framework\v4.0.30319

function fail() {
    echo $*
    exit 1
}

set -o errexit

cmd="$1"
[ -n "$cmd" ] || fail "Missing first command argument: clean or compile"

platform="$2"
[ -n "$platform" ] || fail "Missing second command argument: Win32 or x64"

configurations="$3 $4"
[ -n "$3" ] || fail "Missing third command argument: Debug or Release"

os=$(if [ `uname` == "AIX" ]; then echo linux; else echo `uname -o`; fi)
[ "$os" == 'Cygwin' ] && os="windows"
[ "$os" == 'GNU/Linux' ] && os="linux"
echo Build for operating system $os

inWindows=$(if [ "$os" == "windows" ]; then echo 1; else echo ""; fi)
vcbuild=""
msbuild=""

[ "${PWD/ /_}" == "$PWD" ] || fail "Der Verzeichnispfad darf kein Blank enthalten (vielleicht ist es ein Jenkins-Job mit Blank im Namen?)"

if [ -z "$MAKE_JOBS" ]; then :
    MAKE_JOBS=1
    if [ -s /proc/cpuinfo ]; then :
      MAKE_JOBS=`cat /proc/cpuinfo | grep -w '^processor'|wc -l`
      [ $MAKE_JOBS -le 0 ]  &&  MAKE_JOBS=1
      [ $MAKE_JOBS -gt 8 ]  &&  MAKE_JOBS=8
    fi
    export MAKE_JOBS
fi

if [ $inWindows ]; then \
    [ -n "${WINDOWS_NET_SDK_HOME}" ] || fail 'ERROR: Missing environment variable WINDOWS_NET_SDK_HOME with installation directory of Windows SDK and msbuild.exe (for example "%windir%\Microsoft.NET\Framework\v4.0.30319")'
    msbuild=$(cygpath "${WINDOWS_NET_SDK_HOME}")/msbuild.exe
    [ -f "$msbuild" ] || fail "Missing msbuild.exe: $msbuild"
fi

#--------------------------------------------------------------------------------------------------

function main() {
    cmd_generic_${cmd}
    cmd_${os}_${cmd}
}

#-------------------------------------------------------------------------------------------Generic

function cmd_generic_clean() {
    :
}

function cmd_generic_compile() {
    :
}

#-------------------------------------------------------------------------------------------Windows

function cmd_windows_clean() {
    cmd_windows_cleanWithRm
    visualStudio_clean scheduler
	if [ "$platform" == "Win32" ]; then :
		visualStudio_clean spidermonkey
	fi
    cmd_windows_cleanWithRm
}

function cmd_windows_cleanWithRm() {
    # Weil "vcbuild.exe /clean" nicht immer löschen kann (Fehlermeldung PRJ0008), siehe http://msdn.microsoft.com/en-us/library/hk8k8k4h%28v=vs.80%29.aspx
    for c in $configurations; do :
        PATH=/bin find -type d -ipath "*/$platform/$c" -execdir sh -c "rm -rf {}" \; -prune
    done
    rm -rf {bin,bind,ipch}/*
}

function cmd_windows_compile() {
    visualStudio_compile scheduler
	if [ "$platform" == "Win32" ]; then :
		visualStudio_compile spidermonkey
	fi
}

function visualStudio_clean() {
    package=$1
    msbuild /target:clean $package-vs2010.sln /verbosity:minimal
}

function visualStudio_compile() {
    package=$1
    msbuild $package-vs2010.sln /verbosity:minimal
}

function msbuild() {
    for c in $configurations; do :
        echo $msbuild /nologo /m:$NUMBER_OF_PROCESSORS /property:Configuration="$c" /property:Platform="$platform" $*
        "$msbuild" /nologo /m:$NUMBER_OF_PROCESSORS /property:Configuration="$c" /property:Platform="$platform" $*
    done
}

#---------------------------------------------------------------------------------------------Linux

function cmd_linux_clean() {
    make clean
}

function cmd_linux_compile() {
    make scheduler spidermonkey
    provide_binaries_as_resources
}

function provide_binaries_as_resources() {
    rm -rf generated-java-resources/*
    dir="generated-java-resources/test/com/sos/scheduler/engine/kernelcpp/bin-test"
    mkdir -p "$dir"
    ln -s ../../../../../../../../bin/{libscheduler.so,scheduler,libspidermonkey.so} "$dir/"
}

function searchAndDestroySubDirectory() {
    subDirName="$1"
    PATH=/bin find -type d -and -name "$subDirName" -execdir sh -c "rm -rf {}" \;
}

#--------------------------------------------------------------------------------------------------

main
