#! /bin/bash
# $Id$

. make/make-all.include


do_make 3rd_party/libxml2          libxml2.a                                           || exit
do_make 3rd_party/libxslt/libxslt  libxslt.a                                           || exit
#do_make 3rd_party/regexp          libregexp.a                                         || exit
do_make zschimmer                  libzschimmer.a                                      || exit
do_make kram                       all                                                 || exit
#do_make kram                      libkram.a                 $BIN_DIR/sos.mail.jar     || exit
do_make file                       libfile.a                                           || exit
do_make fs                         libfs.a                                             || exit
do_make javaproxy                  libjavaproxy.a                                      || exit
### do_make scheduler                  $BIN_DIR/sos.spooler.jar  $BIN_DIR/scheduler        || exit
do_make scheduler                  $BIN_DIR/scheduler        || exit
do_make scheduler                  $BIN_DIR/setuid                                     || exit

#do_make zschimmer            libsosperlscript.a                                  || exit
