#! /bin/bash

# $Id: prepare_archive_version 11247 2005-01-11 23:22:22Z jz $
# Auf siel.sos zu installieren (bin/prepare_archive_version)
# Initialisiert die neue archivierte Version mit der alten, damit nachfolgendes rsync schneller läuft.


group="$1"
group_with_version="$2"
dest="Archive/$group/$group_with_version"

[ ! -h scheduler ]  &&  exit

link="`readlink $group`"

if [ "$link" != "$dest" ]  &&  [ "$link" != "$dest/" ]; then
    mkdir -p $dest  ||  exit 1
    cp -a $group/* $dest/
fi

exit 0  # Fehler ignorieren wir
