#! /bin/sh
# $Id: sosmake 11348 2005-03-24 10:17:34Z jz $

# sosmake erwartet, daß es im lib-Verzeichnis gestartet wird
ENTW_DIR=../../..
MAKE_DIR=$ENTW_DIR/prod/make
jobs=1

(
    cd ../lib

    if [ "$1" = "all" ]; then
        $0 kram && $0 file && $0 rapid && $0 fs && $0 kram soswnmai.o && $0 file hostcopy && $0 fs sosfs
    else
        prod=$1
        export prod
        shift 1;

        SYSTEM=`cd .. && basename \`pwd\` `;
        export SYSTEM
        SYSTEM_UNIX=1;
        export SYSTEM_UNIX
        if [ -f /etc/dfs/dfstab ]
        then \
            SYSTEM_SOLARIS=1
            export SYSTEM_SOLARIS
        else \
            SYSTEM_LINUX=1
            export SYSTEM_LINUX
        fi

         if [ "$prod" = "clean" -o "$prod" = "clean_all" ]
         then
            echo "Löschen aller Objektdateien"
            echo "Abbruch mit Ctrl-C innerhalb von 5 Sekunden"
            sleep 5
            echo "Jetzt wird gelöscht ..."
            /bin/rm -f *.o
            /bin/rm -f *.d
            /bin/rm -f Templates.DB/*
            /bin/rm -r Templates.DB
            if [ "$prod" = "clean_all" ]
            then
                /bin/rm -f ../../win/lib/*.obj
                /bin/rm -f ../../win/lib/*.lib
                /bin/rm -f ../../win/bin/*.exe
                /bin/rm -f ../../win/bin/*.map
            fi
         else
            $MAKE_DIR/delcr $ENTW_DIR/prod/$prod/*.cxx $ENTW_DIR/prod/$prod/*.h $ENTW_DIR/prod/$prod/*.inl $ENTW_DIR/prod/$prod/*.tpl

            if [ $SYSTEM_SOLARIS ]
            then
                gmake -r --jobs=1 -f $ENTW_DIR/prod/make/makefile.std.gnumake $*
            else
                gmake -r --jobs=$jobs -f $ENTW_DIR/prod/make/makefile.std.gnumake $*
            fi
         fi
    fi
)
